### PR TITLE
Orphaned packages and droplets cleanup jobs

### PR DESCRIPTION
**Pull request by rkoster**
This PR addresses the orphaned packages issue raised [here](https://github.com/cloudfoundry/cloud_controller_ng/issues/440).

The cleanup of orphaned droplets will be submitted as a separated PR.

### CODE REVIEW

**Comment by rkoster** [comment]
Since submitting orphaned droplets cleanup as a separate PR would result in merge conflicts I have added it to this PR.

**Comment by dieucao** [comment]
Thanks @rkoster for the PR.  We'll try to get a quick sanity check code review some time next week and then I'll prioritize it for deeper review after that.

**Comment by utako** [comment]
Hi @rkoster,

As of [this story](https://www.pivotaltracker.com/story/show/109604284), we'll be making some changes to our blobstore client so there will be a few changes to make with regards to how this delayed job interacts with files.

Our main concern is how we load the blobstore files into memory and interact with them for each type of file system (NFS, s3, WebDAV, etc). For instance, the S3 fog client is smart enough to not load all blobstore files into memory, but this won't be the case for WebDAV. In WebDAV's case, we'll have to figure out a way to load the files in an enumerable object or something equally conservative with memory use. In addition to this concern, we are currently working on a client wrapper interface in which we'll be removing the "#files" method as part of the aforementioned story, so we'll have to incorporate those changes into the implementation of droplet/package orphan mitigation. 

Feel free to comment here or ping us if you have any ideas about how to elegantly solve the challenges mentioned above. We'll be happy to answer any questions you might have about the changes we're making to the blobstore client, especially on completion of story #109604284.

Thanks for your patience,
@utako, CF CAPI Team

**Comment by rkoster** [comment]
I would say the best place for solving the above would be the client wrapper. It could  a #files method which would returns an enumerable object?

**Comment by simonleung8** [comment]
Hi @rkoster,

We're going to keep this PR open and revisit it when we finish the [story](https://www.pivotaltracker.com/story/show/109604284) to rewrite the blobstore clients.

Thanks,
@simonleung8 & @youreddy 
CF CAPI Team

**Comment by dieucao** [comment]
As discussed with @rkoster I'm going to close this PR because the scope of work remaining is large and he's currently focused on other things.

@smoser-ibm FYI, this could be a useful thing to consider for the bits service/[Flintstone team](https://www.pivotaltracker.com/n/projects/1406862) at some point down the road.  It's a valid pain point that at times there are blobs that are orphaned and no good way to clean them up from the blobstore.

**Pull request closed without merging**
