### PR TITLE
Allow space supporter to get ssh_enabled app feature and to access apps in the stack

### PR DESCRIPTION
**Pull request by mariash**
Allow space supporter to get ssh_enabled app feature and to access apps in the stack.

Endpoints:
GET /v3/apps/:guid/ssh_enabled
GET v3/stacks/:guid/apps

Issue #2410

* [X] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/CONTRIBUTING.md)

* [X] I have viewed, signed, and submitted the Contributor License Agreement

* [X] I have made this pull request to the `main` branch

* [X] I have run all the unit tests using `bundle exec rake`

* [ ] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng#cf-acceptance-tests-cats)

### CODE REVIEW

**Comment by monamohebbi** [comment]
### Acceptance
#### Setup 
Pushed app dora from cf-acceptance-tests repo as admin.

#### Behavior check
Running `cf curl v3/stacks/:guid/apps` as supporter user and developer user returns the same result. 
Running `cf curl v3/apps/$(cf app dora --guid)/ssh_enabled` as supporter user and developer user returns the same result. 

Additionally I tested that a stack associated with an app dora2 in a different space would not show dora2's info via 
```
 cf curl v3/stacks/f4492bdc-2e16-43d9-a6f7-fb867035d6d3/apps
{
   "pagination": {
      "total_results": 0,
      "total_pages": 1,
      "first": {
         "href": "https://api.stream-dart.capi.land/v3/stacks/f4492bdc-2e16-43d9-a6f7-fb867035d6d3/apps?page=1&per_page=50"
      },
      "last": {
         "href": "https://api.stream-dart.capi.land/v3/stacks/f4492bdc-2e16-43d9-a6f7-fb867035d6d3/apps?page=1&per_page=50"
      },
      "next": null,
      "previous": null
   },
   "resources": []
}
```
LGTM!

**Review by sweinstein22 — CHANGES_REQUESTED** [review]
### Code Check

Mostly looks good, a minor detail - we've had [conversations previously](https://github.com/cloudfoundry/cloud_controller_ng/pull/2343#pullrequestreview-694404214) about avoiding using a specific role name when testing things that are separate from explicit permissions tests. To that end, if we could change the ['as a space developer' context](https://github.com/cloudfoundry/cloud_controller_ng/pull/2431/files#diff-736eb52ed00531b22ccd8cfed45e6f1367debef2ac98c83834e23679d69032c0R306) to 'as a permitted user' that would be great. Generally I'm trying to avoid creating a pattern where folks may feel like they need to copy the whole context when introducing a new role, unless there's an outlier case.

### Docs Check

For `GET /v3/apps/:guid/ssh_enabled` it looks like we missed the 'Experimental' note, but otherwise looks good!

**Review by sweinstein22 — APPROVED** [review]
Made one minor change, we needed to include the new stack endpoint in the docs index so it appears in the sidebar, but otherwise looks good. I'm going to let the checks run but otherwise this should be good to merge in!

**Comment by moleske** [comment]
> 
> 
> Made one minor change, we needed to include the new stack endpoint in the docs index so it appears in the sidebar, but otherwise looks good. I'm going to let the checks run but otherwise this should be good to merge in!

D'oh! Thanks for catching that!

**Pull request merged**
