### PR TITLE
Add V3 list service brokers endpoint

### PR DESCRIPTION
**Pull request by AartiKriplani**
This PR adds a `GET /v3/service_brokers` endpoint for listing service brokers registered with the platform. Documentation is included.

Tracker stories for reference: [[1]](https://www.pivotaltracker.com/story/show/161809195) [[2]](https://www.pivotaltracker.com/story/show/162088299) [[3]](https://www.pivotaltracker.com/story/show/162088407)

cc @AartiKriplani @williammartin @georgi-lozev @FlorentFlament

### CODE REVIEW

**Comment by AartiKriplani** [comment]
Unfortunately had to open a new one as I'm unable to reopen https://github.com/cloudfoundry/cloud_controller_ng/pull/1264

**Comment by AartiKriplani** [comment]
Codeclimate issues can be ignored, we need to change the rules in the checker

**Comment by nmaslarski** [comment]
Review is requested from the VAT team, don't merge before.

**Comment by luan** [comment]
This looks exactly like I would've implemented that according to existing patterns.
The only thing that's missing is a request spec with all the permission checking that we do in other resources such as domains/routes: https://github.com/cloudfoundry/cloud_controller_ng/blob/master/spec/request/routes_spec.rb

**Comment by psparks123** [comment]
Supraja and I agree with Luan, your implementation looks great overall! Here are a few suggestions/comments:
- While we were working on domains, we decided to no longer write controller specs and to instead use the request spec to test controller behavior including permissions. Refer to [this story](https://www.pivotaltracker.com/story/show/165075402) for the discussion regarding this decision. 
- For permissions testing in the request spec, we decided to use shared examples (https://github.com/cloudfoundry/cloud_controller_ng/blob/master/spec/request_spec_shared_examples.rb). You can find examples in the request specs for routes and domains. 
- For the domains fetcher, we didn't make a separate domain fetcher and domain list fetcher. We combined it into one DomainFetcher with a fetch method that fetches all the domains and then applies filters based on parameters specified in the message: (https://github.com/cloudfoundry/cloud_controller_ng/blob/2df0cbcd494f24766dfe396d1e92f07cb7b4ef52/app/fetchers/domain_fetcher.rb). This can be useful if there are complex permissions checking steps involved.

**Comment by blgm** [comment]
- We have delete the controller spec as suggested, the tests that it contained are duplicated elsewhere
- Regarding the shared examples pattern for permissions testing, we think this is a good idea.  We think it makes sense to move to this pattern in a [future chore](https://www.pivotaltracker.com/story/show/165999827) and get this PR merged, as it's already an old PR.  We have renamed our original acceptance test to be a request spec, as it contains the right tests.

**Pull request merged**
