### PR TITLE
Allow space application supporter to access specific service binding …

### LINKED ISSUE #2241: Allow space application supporter to access specific service binding endpoints.
## Issue

Allow space supporter to access specific **service binding** endpoints. 

## Context

We are introducing a [new role](https://github.com/cloudfoundry/cfar-proposals/issues/22) and we want to make sure it has the right access.

## Expected result
A space supporter should be able access the following endpoints:

POST /v3/service_credential_bindings
DELETE /v3/service_credential_bindings
GET /v3/service_credential_bindings
GET /v3/service_credential_bindings/:guid
GET /v3/service_credential_bindings/:guid/parameters

A space supporter should get a 403 unauthorized when attempting to curl the following endpoints:

PATCH /v3/service_credential_bindings/:guid

A space supporter should get a 404 when attempting to curl the following endpoints:

GET /v3/service_credential_bindings/:guid/details 

## Acceptance
A space supporter would see the same info as a space developer assigned to the same space for these and only these service binding endpoints.

## Documentation
When I browse to any of these endpoints on [v3 docs](https://v3-apidocs.cloudfoundry.org/version/3.99.0/index.html) I can see the Space Application Supporter role in the list of permitted roles with an indication that this role is not fully implemented and the permissions will be changing.

### PR DESCRIPTION
**Pull request by iaftab-alam**
Closes #2241

* [x] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/CONTRIBUTING.md)

* [x] I have viewed, signed, and submitted the Contributor License Agreement

* [x] I have made this pull request to the `main` branch

* [x] I have run all the unit tests using `bundle exec rake`

* [ ] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng#cf-acceptance-tests-cats)

### CODE REVIEW

**Comment by sweinstein22** [comment]
Hi @iaftab-alam , looks like the other PR that had your name on it got merged in/the CLA signature came through on that one. Is the intent for this PR to turn into a PR addressing https://github.com/cloudfoundry/cloud_controller_ng/issues/2241 or should we close this one out?

**Comment by iaftab-alam** [comment]
hey @sweinstein22,

Please don't close this PR. Indeed it is intended to address this #2241. 
WIP

Regards,
Aftab

**Comment by monamohebbi** [comment]
Hello @iaftab-alam,

This PR looks ready for acceptance, but just given the comment history I wanted to confirm that with you first.

**Comment by iaftab-alam** [comment]
hey @monamohebbi,

Thank you for your comment, Yes, this draft is almost ready for a PR. However, can you please comment on its [user story](https://github.com/cloudfoundry/cloud_controller_ng/issues/2241), there I had a question and need some clarification. Once it's final, it will be ready for merging.

Regards,
Aftab

**Review by monamohebbi — CHANGES_REQUESTED** [review]
### Acceptance

#### Create
Successfully was able to create a service binding between a visible app and service as a space supporter role

#### Get
Curled list and show endpoint as space supporter and dev. Confirmed there was no difference in output.

#### Delete
Successfully deleted service binding as space supporter.

### Changes Requested
I am now able to update service credential bindings when I am expecting a 403

Also there seems to be a very unfortunate and difficult to debug error on the `/parameters` endpoint: 

```
{
  "errors": [
    {
      "code": 10001,
      "detail": "The service broker returned an invalid response. Status Code: 500 Internal Server Error, Body: {\n  \"error\": true,\n  \"message\": \"Behavior object is missing key: fetch_service_binding (tried to lookup plan_id 77f63287-491e-425d-9b1f-f88b19cf87ec)\",\n  \"path\": \"http://fake-routable-service.#{domain}/v2/service_instances/c8
754c1c-b0ec-42ba-97b2-e4cec9b367ab/service_bindings/471f0cf5-fb75-4fee-9e47-fa5f266bd7d7\",\n  \"timestamp\": \"2021-07-28 19:09:25 +0000\",\n  \"type\": \"500\",\n  \"backtrace\": [\n    \"/home/vcap/app/service_broker.rb:121:in `behavior_for_type'\",\n    \"/home/vcap/app/service_broker.rb:298:in `block in <class:ServiceBroker>'\",\n    \"/home/vcap/deps/0/v
endor_bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1674:in `call'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1674:in `block in compile!'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (3 levels) in route!'\",\n    \"/home/vcap/deps/0/vendor_
bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (2 levels) in route!'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'\",\n    \"/home/vcap/deps/0/ve
ndor_bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `catch'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7
.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `each'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib
/sinatra/base.rb:1101:in `block in invoke'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `d
ispatch!'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'\",\n    \"
/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7
.0/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'\",\n    \"/home/vcap/deps/0/
vendor_bundle/ruby/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'\",\n    \"/home/vc
ap/deps/0/vendor_bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/logger.rb:17:in `call'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/common_logger.rb:38:in `call'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:253:in `call'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/sinatra
-2.1.0/lib/sinatra/base.rb:246:in `call'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'\",\n    \
"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `block in call'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1769:in `synchronize'\",\n    \"/home/vcap/deps/0/vendor_bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `call'\",\n    \"/home/vcap/deps/0/vendor
_bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/handler/webrick.rb:95:in `service'\",\n    \"/home/vcap/deps/0/ruby/lib/ruby/2.7.0/webrick/httpserver.rb:140:in `service'\",\n    \"/home/vcap/deps/0/ruby/lib/ruby/2.7.0/webrick/httpserver.rb:96:in `run'\",\n    \"/home/vcap/deps/0/ruby/lib/ruby/2.7.0/webrick/server.rb:307:in `block in start_thread'\"\n  ]\n}",
      "title": "CF-ServiceBrokerBadResponse"
    }
  ]
}
```
Very strangely the stack trace seems to be dipping into Sinatra and v2 code and packages like `/home/vcap/app/service_broker.rb` which I couldn't even find on my deployment. Does this seem like it might be related to the change you made?

**Comment by iaftab-alam** [comment]
hey @monamohebbi,

Thanks for the report. I will look into this matter and report back.

Regards,
Aftab

**Comment by iaftab-alam** [comment]
Hey @monamohebbi again,
 
Update: 
for PATCH, the test suggest it should be 403, can you share how you tested it.

for /parameters, it's looks from the logs, the errors are originating from service broker.

Regards,
Aftab

**Comment by monamohebbi** [comment]
When logged in as the space supporter I run `cf curl v3/service_credential_bindings` and grab a guid of a visible binding. Then I run `cf curl -X PATCH v3/service_credential_bindings/2734b4ab-0fad-40a3-9d52-67f5c9a71f5f`
```
{
  "guid": "2734b4ab-0fad-40a3-9d52-67f5c9a71f5f",
  "created_at": "2021-07-29T17:20:04Z",
  "updated_at": "2021-07-29T17:20:07Z",
  "name": "louie-binding-routable-to-dora",
  "type": "app",
  "last_operation": {
    "state": "succeeded",
    "description": null,
    "type": "create",
    "updated_at": "2021-07-29T17:20:07Z",
    "created_at": "2021-07-29T17:20:07Z"
  },
  "metadata": {
    "labels": {

    },
    "annotations": {

    }
  },
  "relationships": {
    "service_instance": {
      "data": {
        "guid": "c8754c1c-b0ec-42ba-97b2-e4cec9b367ab"
      }
    },
    "app": {
      "data": {
        "guid": "0e58e321-4d06-4251-a4fb-8379b42e829b"
      }
    }
  },
  "links": {
    "self": {
      "href": "https://api.clover-horse.capi.land/v3/service_credential_bindings/2734b4ab-0fad-40a3-9d52-67f5c9a71f5f"
    },
    "details": {
      "href": "https://api.clover-horse.capi.land/v3/service_credential_bindings/2734b4ab-0fad-40a3-9d52-67f5c9a71f5f/details"
    },
    "service_instance": {
      "href": "https://api.clover-horse.capi.land/v3/service_instances/c8754c1c-b0ec-42ba-97b2-e4cec9b367ab"
    },
    "parameters": {
      "href": "https://api.clover-horse.capi.land/v3/service_credential_bindings/2734b4ab-0fad-40a3-9d52-67f5c9a71f5f/parameters"
    },
    "app": {
      "href": "https://api.clover-horse.capi.land/v3/apps/0e58e321-4d06-4251-a4fb-8379b42e829b"
    }
  }
}
```

I know this is an odd test since I am not actually sending in any parameters but I would still expect a 403.

When I do the same steps with apps for example:
```
cf curl -X PATCH v3/apps/$(cf app dora --guid)
{
  "errors": [
    {
      "detail": "You are not authorized to perform the requested action",
      "title": "CF-NotAuthorized",
      "code": 10003
    }
  ]
}
```
I'll do some more digging into what might be wrong with my service to test the parameters endpoint properly.

**Comment by iaftab-alam** [comment]
Hey @monamohebbi,

We have double checked with the service broker and user provided service, and we cannot patch service binding for either as a space supporter. 

We can't reproduce the same error despite running unit test and setting up local environment and as a result getting 403 for PATCH. Can you check on your side again or we suggest to have call? What is you opinion on this?

Regards
Aftab

**Review by sweinstein22 — CHANGES_REQUESTED** [review]
### Code Check

Changes look good, use patterns established for this work. I noticed that for `GET /v3/service_credential_bindings/:guid/details` we were expecting a `404`, looking at the comments in the issue it seems like that's the intended end result. I've updated the description of the issue to reflect that discussion.

### Docs Check

Looks like most of the endpoints were changed correctly, but `GET /v3/service_credential_bindings/:guid/details` did get included in the list of endpoints the Space Supporters can access. If we could roll back that docs change that would be great, thanks!

**Comment by iaftab-alam** [comment]
Hey @sweinstein22,

Thank you for feedback. Changes are done. You can further proceed with the PR.

Regards,
Aftab

**Review by sweinstein22 — APPROVED** [review]
Great, thanks! Once Mona has had a chance to complete the behavioral check this should be ready to merge, unless further changes are required as a result of that review.

**Comment by monamohebbi** [comment]
LGTM!

I redeployed and got the same patch behavior, not quite sure what was going on with the other bosh env I had set up. I also traced some of the errors I was getting from the `/parameters` endpoint and it looks like we're getting them after the permissions checks are passing so that front should be ok too.

**Review by sweinstein22 — APPROVED** [review]

**Comment by sweinstein22** [comment]
We're troubleshooting something in the pipelines, will merge this in once they're unblocked

**Pull request merged**
