### PR TITLE
Bump RubyZip to v1.2.2

### PR DESCRIPTION
**Pull request by tcdowney**
RubyZip has now released a new version that includes the following
 commit that the buildpacks team contributed:

 https://github.com/rubyzip/rubyzip/commit/c787d94852b7d3e90212e8f7b08ad6ab6279c74d

Will probably just merge this normally, but wanted to test some of our PR integrations.

* Links to any other associated PRs

https://github.com/rubyzip/rubyzip/pull/358

* [x] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/CONTRIBUTING.md)

* [x] I have viewed, signed, and submitted the Contributor License Agreement

* [x] I have made this pull request to the `master` branch

* [x] I have run all the unit tests using `bundle exec rake`

* [x] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng#cf-acceptance-tests-cats)

### CODE REVIEW

**Comment by selzoc** [comment]
No synk check?

**Comment by tcdowney** [comment]
@selzoc what is this?
screen shot 2018-10-01 at 12 08 20 pm

**Comment by selzoc** [comment]
The permissions must be such that only you can see them @tcdowney:
screen shot 2018-10-01 at 1 32 33 pm

**Comment by tcdowney** [comment]
This was done in https://github.com/cloudfoundry/cloud_controller_ng/commit/d03baa6b6d6f32ebff5644e303c6e6ea1b3c364a

**Pull request closed without merging**
