### PR TITLE
ISSUE-2040-favor-401-over-429

### PR DESCRIPTION
**Pull request by svkrieger**
Thanks for contributing to cloud_controller_ng. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:

This is a proposal for issue #2040 
This PR changes the behaviour of the "SecurityContextSetter" middleware. This will now check which return code it got back from the next middleware in the call chain. If it gets back a 429 from the "RateLimiter" middleware, it will check if the token is expired, but in general valid. If so, the response is changed from 429 to 401.

The information, whether the token is expired, but in general valid, is retrieved from the SecurityContext.
The SecurityContext was extended by a function which returns true, if the context contains ":expired_token".

The "UaaTokenDecoder" was also changed. It now calls a newly implemented function in the cf_uaa_lib "decode_at_reference_time_exp_warn_only". This function will return the decoded token within the "TokenExpired" exception, if the token is expired, but passed all other checks.
This enables us to execute the remaining checks like the uaa issuer validation.
If all checks in the UaaTokenDecoder passed as well, we throw the catched "TokenExpired" exception again, which will be catched in the "SecurityContextConfigurer", which will store ":expired_token" in the context.
The token is still considered invalid, but the different value in the context enables the "SecurityContextSetter" to distinguish between a bad token (all other cases except expired tokens) and an expired token.

* An explanation of the use cases your change solves

As above mentioned issue describes, the change basically favors 401 over 429 for expired tokens.

* Links to any other associated PRs

This PR depends on the following PR: https://github.com/cloudfoundry/cf-uaa-lib/pull/70

* [x] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/CONTRIBUTING.md)

* [x] I have viewed, signed, and submitted the Contributor License Agreement

* [x] I have made this pull request to the `main` branch

* [ ] I have run all the unit tests using `bundle exec rake`

* [ ] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng#cf-acceptance-tests-cats)

### CODE REVIEW

**Comment by sethboyles** [comment]
I think this approach is reasonable and I would be OK with you all moving forward with this solution.  

When writing tests, can you include one that ensures that when calling an Unauthenticated request with an Expired but Otherwise Valid token, that rate limiting is still being applied?

**Comment by svkrieger** [comment]
Hi @sethboyles,

great! Regarding your specific test case. We saw in the meantime that the current solution unfortunately also changes the response from 429 to 401 for requests to unauthenticated endpoints, which don't skip the rate limit check in case the token is expired but otherwise valid.
This is not a 100% clean solution, but the cases where an unauthenticated endpoint returns a 401 are very rare. This is because most of the endpoints which don't require authentication, skip the rate limiting. Examples for that are the info endpoints. Endpoints which do not require authentication and would return a 401 in case the token is expired, but valid otherwise are marketplace calls. In this case we think it can be even positive to send a 401 because the CF cli will refresh the token and the returned service offering will be the same and not shortened because the user isn't authenticated anymore. The benefit of the current solution is that the rate limiting itself works just as before and only the response, which will be send to the client is changed.
The following table summarises the changes for the different endpoints and requests:

Endpoint   Type | Token   sent? | Token   valid? | Reason | Skip   rate limiting? | Rate   limit exceeded? | Before | Current   solution
-- | -- | -- | -- | -- | -- | -- | --
Unauthenticated | No | - | - | No | No | 200 | 200
Unauthenticated | No | - | - | No | Yes | 429 | 429
Unauthenticated | No | - | - | Yes |   | 200 | 200
Unauthenticated | Yes | No | Bad   token | No | No | 200 | 200
Unauthenticated | Yes | No | Token   expired | No | No | 200 | 200
Unauthenticated | Yes | No | Bad   token | No | Yes | 429 | 429
Unauthenticated | Yes | No | Bad   token | Yes | - | 200 | 200
**Unauthenticated** | **Yes** | **No** | **Token expired** | **No** | **Yes** | **429** | **401 (unwanted)**
Unauthenticated | Yes | No | Token   expired | Yes |   | 200 | 200
Unauthenticated | Yes | Yes | - | No | No | 200 | 200
Unauthenticated | Yes | Yes | - | No | Yes | 429 | 429
Unauthenticated | Yes | Yes | - | Yes |   | 200 | 200
  |   |   |   |   |   |   |  
Authenticated | No | - | - | No | No | 401 | 401
Authenticated | No | - | - | No | Yes | 429 | 429
Authenticated | Yes | No | Bad   token | No | No | 401 | 401
Authenticated | Yes | No | Token   expired | No | No | 401 | 401
Authenticated | Yes | No | Bad   token | No | Yes | 429 | 429
**Authenticated** | **Yes** | **No** | **Token expired** | **No** | **Yes** | **429** | **401 (wanted)**
Authenticated | Yes | Yes | - | No | No | 200 | 200
Authenticated | Yes | Yes | - | No | Yes | 429 | 429

We don't see any chance to distinguish between endpoints which require authentication and which don't in the middlewares, as this decision is made in the super class of the endpoints (ApplicationController) and the basis for this decision is the corresponding action e.g. "index", which is derived by the router after all middlewares were executed. We could hardcode all endpoints which don't require authentication into an array, but that's kinda hacky.
We'll go forward for now with implementing some tests. Let us know if you have other ideas or any concerns.

**Comment by sethboyles** [comment]
@svkrieger thank you for that chart!  It really helps when trying to think about all the different cases here.

Considering we by default have a higher rate limit for authenticated requests ([defined here](https://github.com/cloudfoundry/capi-release/blob/develop/jobs/cloud_controller_ng/spec#L1013)), in the 'unwanted' case, that is probably a good change.  Letting a user know their token is expired would let them refresh their token and potentially get access to a higher rate limit.  

In general, it does seem a little odd to accept invalid tokens (expired or bad or otherwise) for unauthenticated requests. I wonder if it is just simpler to return 401 for invalid tokens wholesale, or at least when rate limiting is exceeded.  So for example, for this case: 


Endpoint   Type | Token   sent? | Token   valid? | Reason | Skip   rate limiting? | Rate   limit exceeded? | Before | Current   solution
-- | -- | -- | -- | -- | -- | -- | --
Unauthenticated | Yes | No | Bad   token | No | Yes | 429 | 429

I think there would be value in returning a 401 here as well because it could also give a user a higher rate limit.

**Comment by svkrieger** [comment]
@sethboyles we discussed internally whether it would make sense to return a 401 generally in case the request was sent with an invalid token to an endpoint which does not require authentication. We don't think that this is a good idea as in general a 401 should be only returned when the requested resource requires authentication.

We also think that returning a 429 in case the rate limiting is exceeded and the token is a bad token (can't be decoded, wrong UAA issuer, not an access token) is preferable. We think we should only return the beneficial 401 to users which at least sent a valid, but expired token. If the token is a bad token, it is likely that the client won't be able to refresh it anyways (because obviously the client does not know which is the correct UAA or tries to construct an access token by itself).

Please let us know if that makes sense to you as well. In the meanwhile we added tests for the new logic. The checks here won't pass successfully though, until the PR in the cf_uaa_lib was merged and made available in a new release and we change the corresponding version in the Gemfile here. We are also open for feedback on the change in the cf_uaa_lib.

**Comment by sethboyles** [comment]
@svkrieger I'm not sure it's worth it to check if a token is otherwise valid.  We might as well just return 401 for all expired tokens.  This would also simplify the solution and allow us to avoid the requirement of updating the uaa lib.

**Comment by svkrieger** [comment]
Okay then I'd suggest we remove the check, whether it is expired as well, as we can't make sure it would be otherwise valid. In this case we can return a 401 for all bad tokens, including expired ones, right?

Then we can just check in the security_context_setter, if we get a 429, whether the token is invalid, valid or nil. If the token is invalid (including expired) we return a 401. If the token is nil or valid we return the 429.

That would result in the following response changes:
Endpoint   Type | Token   sent? | Token   valid? | Reason | Skip   rate limiting? | Rate   limit exceeded? | Before | Current   solution
-- | -- | -- | -- | -- | -- | -- | --
Unauthenticated | Yes | No | Bad   token | No | Yes | 429 | 401   (new)
Authenticated | Yes | No | Bad   token | No | Yes | 429 | 401   (new)

For the first case it could be a bit confusing though. First the client would receive 200s until the rate limit got exceeded and then it will get 401s. Maybe in this case we should also return the rate limit headers with the 401, to make visible, that the rate limit got exceeded? Again the endpoints which will fall into this case are very rare. We can only think of marketplace calls. Other endpoints which do not require authentication, are skipping the rate limit check.

Let us know if we should go for this solution. Then we will change the implementation accordingly.

**Comment by sethboyles** [comment]
I am in favor of this solution.  You could make the argument for returning a 401 even if the rate limit is not exceeded, the endpoint is unauthenticated, but the token is invalid.  I checked a few other APIs and saw this behavior.

We don't have to go that far, but I think this solution is fine.

**Comment by svkrieger** [comment]
@sethboyles the PR is ready for review. We implemented it as discussed above. The tests reflect the behaviour, we wanted to achieve. We also think that always returning a 401 is a bit out of scope here, as it would require code changes in the endpoints too. Let us know if you have any questions about the current implementation.

**Comment by bruce-ricard** [comment]
Hi, Bruce from UAA here.

I would like to talk about this line:

Endpoint Type | Token sent? | Token valid? | Reason | Skip rate limiting? | Rate limit exceeded? | Before | Current solution
-- | -- | -- | -- | -- | -- | -- | --
Authenticated | Yes | Yes | - | No | Yes | 429 | 429


IMHO there is a larger problem here. Why are we validating the token when we know that the user is being rate limited? 
IMHO the first line of the controller should be something like
```
if is_rate_limited() then
  return 429
```

This seems to completely defeat the purpose of rate limiting, if we still do work and maybe let the UAA be DDOSed because we keep validating the tokens, when we know that we are going to return 429 anyways.

Please share your thoughts.

**Comment by svkrieger** [comment]
@bruce-ricard let me answer your questions:
- First of all, this PR only changes the response of the CC from 429 to 401 in case the token is invalid. I'm pretty confident that this can't open any backdoors or enable DoS attacks.
- The token is and always was decoded before the rate limiting middleware. As to what I saw in the CC coding, the CC fetches the public keys from the UAA once and then uses these to decode the tokens locally, by using the cf-uaa-lib and without calling the UAA for every token. The information, whether the token is valid or not, is needed to distinguish between unauthenticated and authenticated rate limits.
- As long as a valid token comes with the request, the rate limiting applies to the specific user and not to the IP. Even if the IP's rate limit got exceeded, the authenticated request coming from the same IP, won't be rejected.

**Comment by sethboyles** [comment]
Hi @bruce-ricard 

As @svkrieger noted above, we check validity of tokens (if present) for rate limiting as users or clients may have a higher rate limit than unauthenticated clients.

See related configs here: https://github.com/cloudfoundry/capi-release/blob/develop/jobs/cloud_controller_ng/spec#L1013

Does that make sense or do you think there are possible issues with this ?  (this logic is already present in CCNG and not introduced by this PR, by the way)

**Comment by sethboyles** [comment]
Merging.  Thanks for submitting this PR!

**Pull request merged**
