### PR TITLE
Update fingerprint description with list of supported hashes

### PR DESCRIPTION
**Pull request by pivotal-danjahner**
The current version of the CF CLI supports MD5 and SHA1. The forthcoming version will support SHA256 hash verification.

### CODE REVIEW

**Comment by zrob** [comment]
Hi @pivotal-danjahner,  thanks for the update. I understand there are several different formats the fingerprints might take, would you mine adding an example key with a couple example fingerprints?

thanks!
@zrob

**Comment by pivotal-danjahner** [comment]
Sample for the three supported formats: 

Key - 
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDit9zww/zQjmDhbIYuxeiWKyJKTkjNqkxyptI2a5zi1N30k4M/EZnPJyJHJ2RKnl9eIYbdA4jOoiJJLX0U540pCkvb0Il4cYgjUtZsGAHXI4FJc+o74fODxo2dVZlNwoIR7pscgXQSPRigtwo4FDysyQFfDT0S/BptxwZHAK7y8P7waer332ohlpI3mwA0ZibKi52uCoEPqrNoyRXAc1KeUST2PgkjTEWk0GIjxdx2heSVe4ctVEFkmACBpX5bJCS0eKwQr+VZHgK3gMStockof3IBsRYU2PjeW/hDcWCoAdto4wqQbIDr2o2gncl1LBzh1lXS/chBoji8A/zmF4+x djahner@jah.local
```

Accepted hashes (only the value should be included, not the hash type) - 
```
SHA256: 0KmvfcwFCnwQRviOJEwZtnz5qoi76BVb8dm3/vgilCI
SHA1: b8:80:2c:8c:d7:25:ad:2a:b4:8c:02:34:52:06:f7:ba:1f:0d:02:de
MD5: d2:d6:b9:d7:f9:c4:15:70:de:af:c7:36:88:3a:60:12
```

You can obtain these hashes using with the following command with the appropriate hash algorithm `ssh-keygen -lf ssh-key.pub -E SHA256`. SHA1 is a bit odd, because it is required by the CLI in hex format, whereas ssh-keygen returns it in base64. If a user chooses to use that hash, they will need to convert it. 

For that sake of simplicity and security, we should push everyone toward using the SHA256 hash.

**Comment by pivotal-danjahner** [comment]
The CLI update to support sha256 hashes is in v6.25.0 (released yesterday).

**Comment by michaelxupiv** [comment]
Hey @pivotal-danjahner,

Thanks for submitting this PR. I'll go ahead and merge this!

Thanks,
CAPI Community, @michaelxupiv

**Pull request merged**
