### PR TITLE
Upgrade v3 docs favicon to be web 3.0 compatible

### PR DESCRIPTION
**Pull request by Gerg**
- Dynamic chromatic elements
- Spacial orientation adjustment
- More alpha

### CODE REVIEW

**Comment by tcdowney** [comment]
@Gerg can you take a screenshot of your browser tabs and attach it to this PR? That would make it easier to visualize! 👨‍🎨

**Comment by Gerg** [comment]
You can 👁 is here: https://raw.githubusercontent.com/cloudfoundry/cloud_controller_ng/09228237cb3496e7deeef354cfcf219585431ffa/docs/v3/source/images/favicon.ico

**Comment by tcdowney** [comment]
Screen Shot 2019-06-07 at 12 47 37 PM

Wow! Looks downright luxurious. 💎 🥇

**Comment by Gerg** [comment]
Screen Shot 2019-06-11 at 5 47 25 PM

**Comment by tcdowney** [comment]
Thanks @Gerg, you're a modern-day Da Vinci. 🎨 👨‍🎨

**Pull request merged**
