### PR TITLE
Add support for bits-service-based blobstore

### PR DESCRIPTION
**Pull request by petergtz**
Hello CAPI team,

These are the changes to use of the [bits-service](https://github.com/cloudfoundry-incubator/bits-service) based blobstore.

Bits-service is shipped in the [bits-service-release](https://github.com/cloudfoundry-incubator/bits-service-release).

This is still experimental and by default disabled. To enable it, append to CC config.yml:

```yaml
bits_service:
  enabled: true
  public_endpoint: http://bits-service.bosh-lite.com
  private_endpoint: http://bits-service.service.cf.internal
```

* [x] I have made this pull request to the `master` branch
* [x] I have run all the unit tests using `bundle exec rake`
* [x] I have run CF Acceptance Tests on bosh lite

Our CI pipeline is located at [here](https://flintstone.ci.cf-app.com/pipelines/bits-service?groups=all).

Please let us know if you have any questions. 
Thanks,
@petergtz and @tscolari

### CODE REVIEW

**Comment by adowns01** [comment]
Hi @petergtz, 

I'm having problems generating a bit-service manifest. I run 
```
./scripts/generate-default-bosh-lite-manifest
```

and I get 
```
2 error(s) detected:
 - $.jobs.bits-service.networks.default.static_ips: `$.networks` could not be found in the datastructure
 - $.properties.bits-service.public_endpoint: Unable to resolve `jobs.bits-service.networks.default.static_ips.0`: $.jobs.bits-service.networks.default.static_ips @{R[=(( static_ips(0) ))] is a scalar (not} a map or a list)
```

Where are these properties supposed to be set? Do you have a sample manifest I can use to deploy?

Also, your README says that you are using spiff to merge yaml files, when in fact you are using spruce. 


Thanks, 
Amelia

**Comment by petergtz** [comment]
Hi @adowns01,

You're right our manifest generation scripts are broken. We've added [an item to our backlog](https://www.pivotaltracker.com/story/show/126207459) to fix it.

For the time being, please use this [manifest](https://github.com/cloudfoundry/cloud_controller_ng/files/361068/cf-with-bits.yml.zip) for bosh-lite. It's basically a `cf.yml` as you get it from `cf-release/scripts/generate-bosh-lite-dev-manifest` plus a few additions (bits-service job and new properties to CC).

Sorry about our README. It's outdated and we've also added an issue to update it.

Thanks,
@petergtz and @suhlig

**Comment by adowns01** [comment]
Hi @petergtz and @suhlig, 

Using the manifest you provided, I tried to deploy, but got the following error: 

```
Director task 37
  Started preparing deployment > Preparing deployment. Done (00:00:01)

Error 100: Unable to render instance groups for deployment. Errors are:
   - Unable to render jobs for instance group 'hm9000_z1'. Errors are:
     - Unable to render templates for job 'hm9000'. Errors are:
       - Error filling in template 'hm9000.json.erb' (line 41: Can't find property '["hm9000.etcd.machines"]')

```

Does it work when you use it? 

Thanks, 
@adowns01

**Comment by petergtz** [comment]
Hi @adowns01,
(cc @suhlig, @smoser-ibm)

sorry for the late response, I was OOTO.

This error looks like it is unrelated to our changes, because we haven't done anything with hm9000. My assumption is that your cf-release is too new. Can you please try again with https://github.com/suhlig/cf-release/tree/wip-bits-service? It's our own fork, frozen in time, and should match with the deployment manifest I provided you with above.

Btw, we are currently cleaning up our manifest generation and we should soon be able to provide you with a reproducible way, which would then also work with newer versions of cf-release.

Thanks,
Peter

**Comment by SocalNick** [comment]
@adowns01 @petergtz can we confirm which side is waiting on more information to move this PR along?

**Comment by petergtz** [comment]
@SocalNick, @adowns01 Sorry about the confusion. The ball is on our side. We are almost done simplifying the manifest creation. Will give you an update as soon as this available (which should be today or tomorrow).

**Comment by suhlig** [comment]
@adowns01, @SocalNick, 

@petergtz and I fixed the scripts; please follow the [updated README](https://github.com/cloudfoundry-incubator/bits-service-release/blob/master/README.md#deploy-a-cf-on-bosh-lite-with-bits-service-enabled). We just tested it with a CF in bosh-lite that was created using your `recreate_bosh_lite` sprout script.

Please remember to use the cf-release from our [fork](https://github.com/suhlig/cf-release/tree/wip-bits-service).

Thanks for your patience!

**Comment by SocalNick** [comment]
@suhlig @petergtz what's the difference between your fork of cf-release and where it diverged? I think we have to fix it to work with the latest cf-release/develop.

**Comment by sax** [comment]
As @SocalNick mentioned, we're not comfortable merging this until it works with cf-release/develop. We are going to review the code, in any case.

**Comment by sax** [comment]
* `DependencyLocator` being used as a place for boolean config flags
  * `VCAP::Config` would be a better place
* Logic to choose between `BitsServicePacker` and `AppBitsPacker` can live in `DependencyLocator`
  * other classes can ask `DependencyLocator` for the current bits packer
* `ResourceMatchesController`:
  * PR has this as forking logic, which then implements different methods
  * Preferred code would have forking logic in the `DependencyLocator` to provide the correct instance
  * Classes for each type of behavior would be duck-typed, so controller can call the same method(s) on each
* `CloudController::Blobstore::ClientProvider`
  * This is generic, so should not have its initialization signature made specific to the bits service. `Config` is already available from the `DependencyLocator`, so if the `BitsServiceClient` needs specific config, it should be looked up from the `DependencyLocator`. This could be done either in the client itself, or in the `ClientProvider` and injected into the client instance.
  * Right now, it's `if/else webdav/fog`. This is not great, but seems alright with only two supported options. Adding a third, which is dependent on a different team, makes this seem less alright. Maybe this should be made more like an adapter, which can be configured accordingly. The actual clients should implement the same initialization signature, so that other adapters can be made.

We feel that `lib/bit_services` can be externalized as a gem. This will provide a clear boundary between Cloud Controller and Bits service. Moreover, it's a pattern we'd like to encourage external services to follow.
  * References to objects such as `Steno.logger` and `VCAP` configuration can be injected with similar interfaced objects in the gem.
  * While this may not be needed currently, it opens up the gem to be used for further similar uses.
  * We are also wary about having ownership of the client code as it requires knowledge of the corresponding server code to properly maintain it.
  * Defining clear interfaces that services like this should follow will make them easier for the CAPI team to support. We already suffer from significant cognitive load when making changes or bug fixes to services that we interact with, because of the difference in interfaces and in how they are initialized, and the lack of clear boundaries between them.

Here's how we are thinking in terms of modularization:

```
external service     > library/gem             > adapter     > CAPI code
bits-service-release > bits-service-client gem > BitsAdapter > CloudController
```

We're available for further assistance and discussion on Slack and hangouts, if you'd like some more synchronous communication.

Thanks,
@sax and @rizwanreza 
CAPI Team

**Comment by SocalNick** [comment]
@suhlig @petergtz would it be possible to setup a schedule shift so that we can x-team pair with you on the fixes proposed above and getting this to work with the latest cf-release? We could potentially start the x-team pair on Monday, July 25 at 8am PT.

cc @utako

**Comment by smoser-ibm** [comment]
hey @SocalNick - we discussed this in the team, and decided that @suhlig will x-team pair with you starting from Monday, July 25. I'll let Steffen and his pair figure out the starting time, but probably 8am PT is good / better.

**Comment by SocalNick** [comment]
@rizwanreza will be working with @suhlig on Monday.

**Pull request merged**
