### PR TITLE
Generate events for role add/remove for spaces

### PR DESCRIPTION
**Pull request by ScarletTanager**
Subject says it all.

Signed-off-by: Mark St. Godard <stgodard@ca.ibm.com>

[finishes #133060349]

### CODE REVIEW

**Comment by ScarletTanager** [comment]
@SocalNick - any chance we can schedule this one for review?

**Comment by simonleung8** [comment]
Hi @ScarletTanager, the PR overall looks good, but other than the API version failure (which you can ignore), there are some test failures in `users_controller_spec`. Can you fix those and we can have a final look at the PR.

Thanks

**Comment by ScarletTanager** [comment]
@simonleung8 @luan Thanks for the review, I've fixed the failing tests (I promise they worked when we first committed).

**Comment by simonleung8** [comment]
Thanks, merged.

**Pull request merged**
