### PR TITLE
Disable docker apps when docker support is switched off

### PR DESCRIPTION
**Pull request by georgethebeatle**
Disable docker apps when docker support is switched off

     * Add a feature flag for toggling Docker support
     * Filter out docker apps from bulk response  when Docker is disabled
     * Add validation logic to prevent app stage/start operations
     * Do not issue desire app request on routes or instances update for Docker apps  when Docker disabled

### CODE REVIEW

**Comment by georgethebeatle** [comment]
Thanks for the comments. Submitted new version - please take a look

**Comment by fraenkel** [comment]
You did an improper rebase. You ended up merging all the current code in cloud_controller on to your branch. This needs to be redone with all your code rebased on top of the latest code.

Also make sure you pass all the tests.

**Comment by georgethebeatle** [comment]
Hmm, I'm pretty  sure they passed  locally. Seems I messed something  up. I will take care of the mess on Monday

**Comment by georgethebeatle** [comment]
Closing this one in favour of https://github.com/cloudfoundry/cloud_controller_ng/pull/395

**Pull request closed without merging**
