### PR TITLE
Access service usage events as global auditor

### LINKED ISSUE #1403: Not authorized error when fetching service usage events with global auditor role
## Issue

We receive an not authorized error when fetching the service usage events of a pivotal cloud foundry foundation using an user account with the global auditor role assigned. 

## Context

We did create a user with the global auditor role. We chose the role as described in [the docs](https://docs.cloudfoundry.org/concepts/roles.html)

The user has the correct scope when checking with `uaac` client.

## Steps to Reproduce

* Create user with role global auditor
* login via cf cli
* run `cf curl '/v2/service_usage_events'`

## Expected result

We expect to get a list of service usage events as described in [the docs](https://docs.cloudfoundry.org/running/managing-cf/usage-events.html).

## Current result

We receive an not authorized error.

## Possible Fix

We found that the request cycle ends up with an authorization check in https://github.com/cloudfoundry/cloud_controller_ng/blob/master/app/access/service_usage_event_access.rb#L68-L70

From our point of view the implementation is missing the global auditor part. As such the method should look like

```ruby
def index?(*_)
  admin_user? || admin_read_only_user? || global_auditor?
end
```

### PR DESCRIPTION
**Pull request by basiszwo**
This PR closes #1403 

It provides a spec covering the fact that users with role global editor cannot fetch service usage events. Also included is the fix that enables users with role global auditor to fetch the events. 

For more information see #1403 

* [x] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/CONTRIBUTING.md)
* [x] I have viewed, signed, and submitted the Contributor License Agreement
* [x] I have made this pull request to the `master` branch
* [x] I have run all the unit tests using `bundle exec rake`
* [ ] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng#cf-acceptance-tests-cats)

### CODE REVIEW

**Comment by basiszwo** [comment]
I did send the CLA via email.

**Comment by selzoc** [comment]
@chipchilders can you help out with the CLA process here?

**Comment by chipchilders** [comment]
closing / opening to bump CLA bot

**Comment by chipchilders** [comment]
closing / opening to bump CLA bot

**Comment by chipchilders** [comment]
@selzoc all set

**Comment by selzoc** [comment]
> @selzoc all set

Thank you! 🎉

**Comment by basiszwo** [comment]
Are there any news on this? Can I do sth. to move this forward?

**Comment by selzoc** [comment]
Hi @basiszwo ,

Thanks for following up!  I did some poking around at the intent of the global auditor role and found:

> Global Auditor is a user role that has been assigned the cloud_controller.global_auditor scope in UAA. This role has read-only access to all Cloud Controller API resources except for secrets such as environment variables. The Global Auditor role cannot access those values.

So given that, I think it's perfectly ok for global auditors to be able to see service usage events.

**Pull request merged**
