### PR TITLE
Add log-cache endpoint to /info

### PR DESCRIPTION
**Pull request by heycait**
[#168083320]

Signed-off-by: Tom Chen <tochen@pivotal.io>

Thanks for contributing to cloud_controller_ng. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:
Add the log-cache url to /info endpoint

* An explanation of the use cases your change solves
Promotes log-cache to a first class citizen (CF CLI wants).

* Links to any other associated PRs
https://github.com/cloudfoundry/capi-release/pull/153

* [X] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/CONTRIBUTING.md)

* [X] I have viewed, signed, and submitted the Contributor License Agreement

* [X] I have made this pull request to the `master` branch

* [X] I have run all the unit tests using `bundle exec rake`

* [X] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng#cf-acceptance-tests-cats)

### CODE REVIEW

**Comment by heycait** [comment]
Hi CAPI team, it looks like the failing test might be flakey as it's unrelated to our changes and deals with deleting orgs.

**Comment by reneighbor** [comment]
@heycait there's something real funky going on with the commits on this PR - can you please take a look?  lots of unrelated commits on the `log-cache-info` branch.  it looks like you intended to just have one commit adding the endpoint to the `/info` endpoint.

Thanks,
renee && @selzoc

**Comment by kitemongerer** [comment]
@reneighbor That's because we rebased to see if that would fix the issue. To clean things up a bit, we opened a new PR here: https://github.com/cloudfoundry/cloud_controller_ng/pull/1435

**Comment by selzoc** [comment]
OK! we'll close this one and merge that one 👍

**Pull request closed without merging**
