### PR TITLE
preserve existing connection_options passed in from manifest yml

### PR DESCRIPTION
**Pull request by yatzek**
Thanks for contributing to the cloud_controller_ng. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:

* An explanation of the use cases your change solves

* [x] I have viewed signed and have submitted the Contributor License Agreement

I tried but the link (https://www.cloudfoundry.org/individualcontribution.pdf) gives 404

* [ YES] I have made this pull request to the `master` branch

* [YES ] I have run all the unit tests using `bundle exec rake`

* [ NO] I have run CF Acceptance Tests on bosh lite

### CODE REVIEW

**Comment by michaelxupiv** [comment]
Merged in master.

**Comment by michaelxupiv** [comment]
Hey @yatzek,

Thanks for your pull request. However, we noticed that you failed to successfully sign the CLA, which is required for all PRs. There might have been some error registering your initial CLA signature. It would be great if you could please sign it again so that dreddbot properly recognizes it. Otherwise, we would have to revert this PR merge unfortunately.
Reopening this PR for now. 

Thanks,
@michaelxupiv && @zrob

**Comment by yatzek** [comment]
Hi,

Sorry about that, sent now.

Jacek

**Comment by chipchilders** [comment]
@michaelxupiv We have the CLA on file from @yatzek now. Feel free to merge!

**Comment by michaelxupiv** [comment]
Thanks @yatzek. Closing the issue now, the PR has been merged.

**Pull request closed without merging**
