### PR TITLE
Message bus options

### PR DESCRIPTION
**Pull request by frodenas**
**DO NOT MERGE: it requires https://github.com/cloudfoundry/cf-message-bus/pull/3 to be merged and update the Gemfile**

* A short explanation of the proposed change: Allows overriding some default nats properties

* An explanation of the use cases your change solves:  This will help us to prevent the issue documented at https://github.com/cloudfoundry/cloud_controller_ng/issues/726

* [x] I have viewed signed and have submitted the Contributor License Agreement

* [x] I have made this pull request to the `master` branch

* [x] I have run all the unit tests using `bundle exec rake`

* [ ] I have run CF Acceptance Tests on bosh lite

### CODE REVIEW

**Comment by michaelxupiv** [comment]
Hey @frodenas,

Everything looks good to us. We just had a small question on the usage for `dont_randomize_servers`. How is this preventing message_bus from sending large amounts of nats messages as described (here)[https://github.com/cloudfoundry/cloud_controller_ng/issues/726]? 

Thanks,
CAPI Community Pair - @jberkhahn & @michaelxupiv

**Comment by frodenas** [comment]
@michaelxupiv @jberkhahn Just `max_reconnect_attempts` is really useful for #726.

I added `dont_randomize_servers` because https://github.com/cloudfoundry/cf-message-bus/pull/3 allows now to override this param as well, so the 3 nats options allowed by the gem (`servers`, `max_reconnect_attempts`, `dont_randomize_servers`) could be now set via a deployment manifest if desired.

**Comment by jberkhahn** [comment]
Hey there,

We were able to reproduce the related bug from [issue 726.](https://github.com/cloudfoundry/cloud_controller_ng/issues/726) However, when we tried pulling this change in, and setting max_reconnect_attempts to 10, we don't see any slowdown in the thrashing on port 4222 on the api vm.

Furthermore, when we go and trace the nats traffic on the message bus, we don't see any actual increases in nats messages being received.

Were there any other configuration options you needed locally to get this to work or are we doing something wrong?

Thanks,
@jberkhahn & @ericpromislow 
CF CAPI Team

**Comment by frodenas** [comment]
@jberkhahn & @ericpromislow

Did you manually created a new version of the [cf-message-bus](https://rubygems.org/gems/cf-message-bus) gem and vendored it in this repo?

AFAIK, https://github.com/cloudfoundry/cf-message-bus/pull/3 was merged, but nobody published a new version, at least according to rubygems. Without the new gem version, this PR is useless, and this is why I added a note at the top of the PR description. If somebody can push the new version to rubygems, then I can update this PR with the additional changes.

**Comment by zrob** [comment]
@frodenas 

Since this has been resolved as part of #737 we are not going to bring this in.  That issue fixes the problem where the cloud controller was crashing and restarting when the database had shut down, increasing NATS traffic.

Thanks,
@zrob & @ericpromislow

**Comment by frodenas** [comment]
If #737 fixes the problem, then I'm ok.

**Pull request closed without merging**
