### PR TITLE
Remove perm project code

### PR DESCRIPTION
**Pull request by andy-paine**
The perm project has been discontinued and in the cloudfoundry-attic for
a few years now so it is safe to say nobody is running it. As we work on
permissions, it simplifies things to not have to worry about replicating
behaviour to the perm permissions files and we can combine the queryer
and the cloud_controller/permissions files together

Process followed was:
* Remove perm/*.rb files
* Migrate cloud_controller/permissions.rb + queryer.rb ->
permissions_queryer.rb including spec tests
* Fix places where queryer or permissions object was constructed
* Fix up some places where perm was called explicitly (e.g.
tasks_controller) and remove redundant functions
* Fix tests
* Delete perm related gems
* Search for any other references to perm to check it was fully purged
(e.g. .travis.yml)

* [ ] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/CONTRIBUTING.md)

* [ ] I have viewed, signed, and submitted the Contributor License Agreement

* [ ] I have made this pull request to the `main` branch

* [ ] I have run all the unit tests using `bundle exec rake`

* [ ] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng#cf-acceptance-tests-cats)

### CODE REVIEW

**Comment by elenasharma** [comment]
Hey @andy-paine, we noticed this PR is in draft mode. Is that intentional and you have more you want to do on it before we review it? Or is it ready for us to review?

**Comment by andy-paine** [comment]
Hi @elenasharma - I think with the ongoing work with the Space Application Supporter role, the files this PR touches are undergoing lots of changes and it is going to be quite inconvenient for other collaborators to try and merge this PR right now. I've left it up as a draft as a starting point for doing the perm code cleanup after the Space Application Supporter role work is closer to being finished. I can close it now and reopen/open a new one later if it is easier not having it in the PR backlog?

**Comment by andy-paine** [comment]
I guess this isn't needed anymore since #2405 got merged and caused all the merge conflicts anyway...

**Comment by sweinstein22** [comment]
Sorry about that @andy-paine , I didn't realize you had this sitting in a draft. Thanks for taking time to dig into removing perm and hopefully the merge conflicts aren't too hard to resolve, if we can assist in resolving them let us know

**Pull request closed without merging**
