### PR TITLE
Move V2 API docs to Github Pages

### PR DESCRIPTION
**Pull request by pivotalgeorge**
Thanks for contributing to cloud_controller_ng. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:
Serve the V2 API docs as static GitHub Pages assets, deployed via GitHub Actions

* An explanation of the use cases your change solves
As part of the VMware->Broadcom migration, the infrastructure hosting the current v2 apidocs is being replaced. This provides an opportunity to sunset unneeded apps, lowering the project's maintenance & support burden.

* [x] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/CONTRIBUTING.md)

* [x] I have viewed, signed, and submitted the Contributor License Agreement

* [x] I have made this pull request to the `main` branch

* [x] I have run all the unit tests using `bundle exec rake`

* [ ] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/spec/README.md#cf-acceptance-tests-cats)
  - this PR makes no changes to CAPI behavior

### CODE REVIEW

**Review by moleske — COMMENTED** [review]
Will [capi-ci](https://github.com/cloudfoundry/capi-ci/blob/c50ebee1b6faf66c1e87cbce5927c419151c9b63/ci/pipeline.yml#L847) need to change as well?  Also it seems like maybe this should trigger on capi releases?  It looks like it currently runs on pushes to `main` and `gh-pages`, along with manual workflows, but not on new tags/releases

**Review by moleske — COMMENTED** [review]
Ah just saw that v3 has github pages now, so mimicking that.  This seems reasonable to move over as well.

Or, ya know, just end v2 support 😛

**Comment by pivotalgeorge** [comment]
Yep, v3 is already deploying to GitHub Pages, and it seems like a switch to GitHub Actions is [in-progress](https://github.com/cloudfoundry/cloud_controller_ng/actions/workflows/deploy_v3_docs.yml). The corresponding change to capi-ci would be to remove doc-publishing behavior.

As far as triggering on tags/releases, that sounds good, but this repo (CCNG) doesn't use tags. I'm assuming you mean triggering on releases in [capi-release](https://github.com/cloudfoundry/capi-release), right?

**Comment by sethboyles** [comment]
> As far as triggering on tags/releases, that sounds good, but this repo (CCNG) doesn't use tags. I'm assuming you mean triggering on releases in [capi-release](https://github.com/cloudfoundry/capi-release), right?

I think that's what we'd have to do.  Is that even possible?

**Comment by evanfarrar** [comment]
> > As far as triggering on tags/releases, that sounds good, but this repo (CCNG) doesn't use tags. I'm assuming you mean triggering on releases in [capi-release](https://github.com/cloudfoundry/capi-release), right?
> 
> I think that's what we'd have to do. Is that even possible?

maybe the github actions should run in capi-release? we tag /release in capi release

**Comment by moleske** [comment]
Could tag this repo with the version on the commit that is included in the capi release version.  Then wouldn't have to move the docs.  Also fine with moving the docs and action to capi release so only one place has to be tagged.

Might also be a way to trigger actions across repos but that seems unnecessarily complicated.

I was mostly asking cause I noticed trigger was just on main/gh-pages.  Which may be just fine as long as new versions are created properly.  I'm out of practice on how the old docs did all this cause "it just worked."  So triggering off of tags may not be needed if when a new version is created the pipeline just makes the new version, e.g. on commits like [this](https://github.com/cloudfoundry/cloud_controller_ng/commit/8446149ee6f549bc2f5e68718f4a9e4a4a6025e7), or [this](https://github.com/cloudfoundry/cloud_controller_ng/commit/bea81821077db45deec0d9890641e8fcb9323ad2), or [this](https://github.com/cloudfoundry/cloud_controller_ng/commit/fb16f6f575031154fc781dc7a24a4d8adf3fc67e).  And doc changes to main that aren't new versions just update the release candidate version.

I don't have strong feelings was just curious what the plan is as it is clear vmware/broadcom from George's message is uninterested in hosting the existing docs site (which I'm assuming includes hosting v3 in addition to the v2 George mentions in this pr).  Also don't think any of the above needs to block merging this pr since it has manual triggers and all that for folks to test out first before letting the bots run it

**Comment by philippthun** [comment]
> Yep, v3 is already deploying to GitHub Pages, and it seems like a switch to GitHub Actions is [in-progress](https://github.com/cloudfoundry/cloud_controller_ng/actions/workflows/deploy_v3_docs.yml). The corresponding change to capi-ci would be to remove doc-publishing behavior.

We did not change the v3 docs build process, we only moved the script over to [capi-ci](https://github.com/cloudfoundry/capi-ci/blob/main/ci/docs/build_docs_v3.sh) - and did some improvements like getting rid of git ssh. So both, [release candidate](https://concourse.app-runtime-interfaces.ci.cloudfoundry.org/teams/capi-team/pipelines/capi/jobs/rc-docs-v3) and [final docs](https://concourse.app-runtime-interfaces.ci.cloudfoundry.org/teams/capi-team/pipelines/capi/jobs/publish-docs-v3), are still created by jobs in the Concourse pipeline and the GitHub action [deploy_v3_docs](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/.github/workflows/deploy_v3_docs.yml) is only used to upload the results (the previously used mechanism was discontinued by GitHub beginning of July).

**Comment by pivotalgeorge** [comment]
@philippthun, thanks for the clarification. This PR is just about v2 docs. The Concourse vs. Github Actions decision will be relevant for v3, but as v3 docs are in GH-pages, they will not be impacted by the current impending shutdown.

@moleske
> Could tag this repo with the version on the commit that is included in the capi release version

is [picking-up](https://github.com/cloudfoundry/cloud_controller_ng/pull/3874/files#diff-e34cd92a2ae1a54775a2e16b2d1312915a8ce73162ab81b601b30f7086753cd0R9) version info from [config/version_v2](https://github.com/cloudfoundry/cloud_controller_ng/commits/main/config/version_v2) insufficient?

**Comment by philippthun** [comment]
> This PR is just about v2 docs.

Okay, I see. Would you mind removing the file `.github/workflows/gh_pages_docs_v3.yml` from this PR?

**Comment by pivotalgeorge** [comment]
@sethboyles & @evanfarrar — to followup on the capi-release triggering conversation:

I created a draft PR on the capi-release side: https://github.com/cloudfoundry/capi-release/pull/438
an example triggered run is [#12](https://github.com/pivotalgeorge/cloud_controller_ng/actions/runs/9897433090) - shows up as triggered by me since the secret was set to an access token tied to my account, but In Production™ this would be a bot account.

@moleske would this address your original concern?

**Comment by pivotalgeorge** [comment]
Since today is the last day for the PCF env hosting v2 docs, I say we merge this in to avoid downtime

**Comment by pivotalgeorge** [comment]
After discussing with @sethboyles and @Gerg: Moving the v2 workflow to capi-release. see https://github.com/cloudfoundry/capi-release/pull/440

**Review by sethboyles — APPROVED** [review]

**Pull request merged**
