### PR TITLE
Routing api v2 info

### PR DESCRIPTION
**Pull request by msmykowski**
Added routing_api endpoint to the v2/info endpoint

-routing_api is optional

### CODE REVIEW

**Comment by zrob** [comment]
hey, I'm trying to deploy this to bosh-lite and I'm getting the following error:
`Error 100: Error filling in template `cloud_controller_api.yml.erb' for `api_z1/0' (line 190: Can't find property `["routing_api.enabled"]')`

Where did you intend for this value to come from?

**Comment by dieucao** [comment]
After discussion with @shalako, we think it would be better to take advantage of context path routes and make it available at:

api.system.domain/routing

So potentially this would be:
api.system.domain/routing/v1/routes

Closing this PR.

**Comment by shalako** [comment]
@dieu 

Whether the route is `routing-api.system-domain.com` or `api.system-domain.com/routing`, having the url discoverable on /v2/info still seems valuable. This allows us to change the route later but not break clients. 

Do you plan to remove the urls for logging and authentication from /v2/info also?

**Comment by dieucao** [comment]
@shalako Good point.  Sounds reasonable to make the url discoverable still in /v2/info for that reason.

@zrob had a comment above about the original PR.  Could you have your team review that and resubmit a PR?

**Comment by shalako** [comment]
Yes, we'll resubmit with the new url.

**Pull request closed without merging**
