### PR TITLE
Upgrade to Rails 7.0

### PR DESCRIPTION
**Pull request by Gerg**
Upgrade to Rails 7.0

- Upgrade guide: ~https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-7-0-to-rails-7-1~ https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-6-1-to-rails-7-0
- Branched off of #3576
- Related: https://github.com/cloudfoundry/cloud_controller_ng/issues/3438
- I don't know the best procedure to validate the Delayed Job exit behavior, so I blindly bumped the version. It might be helpful to have a more explicit test procedure for validating the desired behavior.

* [x] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/CONTRIBUTING.md)

* [x] I have viewed, signed, and submitted the Contributor License Agreement

* [x] I have made this pull request to the `main` branch

* [x] I have run all the unit tests using `bundle exec rake`

* [x] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/spec/README.md#cf-acceptance-tests-cats)

```
❯ cats
The following feature-flags are disabled!:
diego_docker
hide_marketplace_from_unauthenticated_users
route_sharing
service_instance_sharing
user_org_creation

Would you like them all enabled? (y/N):
Use CONFIG of /Users/gcobb/workspace/capi-env-pool/flower-kangaroo/integration_config.json
Printing sanitized $CONFIG
{
  "api": "api.flower-kangaroo.capi.land",
  "apps_domain": "flower-kangaroo.capi.land",
  "admin_user": "admin",
  "skip_ssl_validation": true,
  "use_http": true,
  "include_apps": true,
  "include_capi_experimental": true,
  "include_detect": true,
  "include_security_groups": true,
  "include_services": true,
  "include_v3": true,
  "include_tasks": true,
  "include_backend_compatibility": false,
  "include_capi_no_bridge": false,
  "include_container_networking": false,
  "include_credhub" : false,
  "include_docker": false,
  "include_internet_dependent": false,
  "include_isolation_segments": false,
  "include_persistent_app": false,
  "include_private_docker_registry": false,
  "include_privileged_container_support": false,
  "include_route_services": false,
  "include_routing": false,
  "include_routing_isolation_segments": false,
  "include_service_discovery": false,
  "include_service_instance_sharing": false,
  "include_ssh": false,
  "include_sso": false,
  "include_zipkin": false
}
Using Ginkgo Version 2.13.2
Running Suite: CATS - /Users/gcobb/go/src/github.com/cloudfoundry/cf-acceptance-tests
=====================================================================================
Random Seed: 1704217744 - will randomize all specs

Will run 235 of 237 specs
Running in parallel across 4 processes
Running CATs with CF CLI version  cf version 8.5.0+73aa161.2022-09-12

------------------------------
[SynchronizedBeforeSuite] PASSED [24.404 seconds]
[SynchronizedBeforeSuite]
/Users/gcobb/go/src/github.com/cloudfoundry/cf-acceptance-tests/cats_suite_test.go:69

  Captured StdOut/StdErr Output >>
  Running CATs with CF CLI version  cf version 8.5.0+73aa161.2022-09-12

  << Captured StdOut/StdErr Output
------------------------------
SSSS•••••S
------------------------------
P [PENDING]
[windows] Getting instance information scaling memory fails when scaled beyond available resources
/Users/gcobb/go/src/github.com/cloudfoundry/cf-acceptance-tests/windows/instance_reporting.go:51
------------------------------
••S•SS•SSS••S•••S•••S•••S•••SSSS•S•••••SSSSS••S•S•SS•SS••S•SS•S•S••S••••S••SSS•••S•S•SSSSSS••S•••••••SSS•S•SSSS••••
------------------------------
P [PENDING]
Context Paths when another app has a route with a context path routes to app with context path
/Users/gcobb/go/src/github.com/cloudfoundry/cf-acceptance-tests/windows/context_paths.go:87
------------------------------
•SS••••S•SS•SS•SSS•SS••S••SSS••S•SSS•S••••S••••SS•••S••SS
------------------------------
• [37.085 seconds]
[apps] Application Lifecycle pushing makes system environment variables available and validates
/Users/gcobb/go/src/github.com/cloudfoundry/cf-acceptance-tests/apps/lifecycle.go:276

  Captured StdOut/StdErr Output >>
  envValues: {0 10.244.0.139 10.255.158.60 61016 10.244.0.139:61016 [{"external":61016,"internal":8080,"external_tls_proxy":61018,"internal_tls_proxy":61001},{"external":61016,"internal":8080,"internal_tls_proxy":61443},{"external":61017,"internal":2222,"external_tls_proxy":61019,"internal_tls_proxy":61002}]}
  << Captured StdOut/StdErr Output
------------------------------
••S•SS•S••S•••SS•••S•S••SSS••SSS•SS••••SS•S••••SS•••

Ran 128 of 237 Specs in 3590.859 seconds
SUCCESS! -- 128 Passed | 0 Failed | 2 Pending | 107 Skipped


Ginkgo ran 1 suite in 59m58.115305708s
Test Suite Passed
```

### CODE REVIEW

**Comment by tcdowney** [comment]
Isn't this the upgrade guide?
https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-6-1-to-rails-7-0

Also looks surprisingly simple. 😅

**Comment by Gerg** [comment]
Good catch, Tim!

**Comment by moleske** [comment]
@johha might have ideas on how to test that the monkey patch for the Delayed Job exit is still working (based off the [original pr](https://github.com/cloudfoundry/cloud_controller_ng/pull/3183))

**Comment by johha** [comment]
Delayed_job does [not have any changes](https://github.com/collectiveidea/delayed_job/compare/v4.1.9...collectiveidea:delayed_job:v4.1.11) in regards to graceful shutdown and signal handling. 
I did some tests locally with the cats service broker:
- trigger `cf create-service fake-service fake-plan fake-instance` -> SB is configured to have a delay of 40 seconds
- kill the generic worker with `SIGQUIT` after a few seconds
-> worker shutdown gracefully and service instance was  created as expected --> monkey patch still working 🎉 

During the last major rails upgrade we had some issues (#2748). Are we confident (enough?) that something similar will not happen (we have at least one [related test case](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/spec/unit/jobs/deserialization_spec.rb))?

**Review by johha — APPROVED** [review]
We did some manual tests to ensure that Rails v7.x delayed jobs can be deserialized on a Rails v6.1 cc-worker. Also tested the other direction with Rails v6.1 delayed jobs on v7.x cc-workers.
Test setup:
- Create BBL env with CAPI 1.167.0
- Ignore cc-worker/ API VMs
- Deploy CAPI 1.167.0 + Rails 7.x commits
- Execute CATS

This results in ~1900 delayed jobs. CATS succeeded successfully both for Rails v7.0 and v7.1.

=> +1  👍 
We could also directly merge the Rails 7.1 PR if there are no objections

**Comment by johha** [comment]
As there was not further feedback we decided to directly merge the Rails 7.1 PR #3584

**Pull request closed without merging**
