### PR TITLE
Space application supporter revisions

### LINKED ISSUE #2232: Allow space application supporter to access specific revision endpoints.
## Issue

Allow space application supporter to access specific **revision** endpoints. 

## Context

We are introducing a [new role](https://github.com/cloudfoundry/cfar-proposals/issues/22) and we want to make sure it has the right access.

## Expected result
A space application support should be able access the following endpoints:

GET /v3/apps/:guid/revisions
GET /v3/apps/:guid/revisions/deployed
GET /v3/revisions/:guid

## Acceptance
A space application supporter would see the same info as a space developer assigned to the same space for these and only these revision endpoints.

## Documentation
When I browse to any of these endpoints on [v3 docs](https://v3-apidocs.cloudfoundry.org/version/3.99.0/index.html) I can see the Space Application Supporter role in the list of permitted roles with an indication that this role is not fully implemented and the permissions will be changing.

### PR DESCRIPTION
**Pull request by will-gant**
Closes #2232 

* [X] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/CONTRIBUTING.md)

* [X] I have viewed, signed, and submitted the Contributor License Agreement

* [X] I have made this pull request to the `main` branch

* [X] I have run all the unit tests using `bundle exec rake`

* [ ] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng#cf-acceptance-tests-cats)

### CODE REVIEW

**Review by sweinstein22 — COMMENTED** [review]
## Acceptance

### Behavior Check

Ran `cf curl` against `GET /v3/apps/:guid/revisions`, `/v3/apps/:guid/revisions/deployed`, `/v3/revisions/:guid` as both a space app supporter and space developer, confirmed that output looked correct manually and that there was no diff in output:
```
$ diff space-app-supporter-app-guid-revisions space-dev-app-guid-revisions

$ diff space-app-supporter-app-guid-revisions-deployed space-dev-app-guid-revisions-deployed

$ diff space-app-supporter-revisions-guid space-dev-revisions-guid

```

Also confirmed that curing `/v3/revisions/:guid/environment_variables` returns a `403` as a space app supporter

### Code Check

Looks good - implementation looks good and the changes leverage the shared examples where possible. There's a minor thing I'd like to pick at, going to leave it as a separate comment.

### Docs Check

Confirmed that new role has been added to all three endpoints with Experimental indicator, and that docs are rendering correctly

**Review by sweinstein22 — CHANGES_REQUESTED** [review]
Super minor, but we've been aiming to be consistent with the way we've been adding the permissions to the request spec shared examples, specifically using the `ALL_PERMISSIONS + ['space_application_supporter']` structure. I know it's a little counter to what we would normally be aiming to do as far as code duplication, but it'll make it easier for us to go through and refactor `'space_application_supporter'` into the default set for `ALL_PERMISSIONS` down the line if things are consistent among the changes we're making now. If you wouldn't mind swapping that out everything else looks good to go! Thanks for the PR!

**Comment by will-gant** [comment]
@sweinstein22 Many thanks for the feedback. You're right - it's going to be easier to work on in future if we keep things like that consistent across these new files. I've implemented the change you requested. Let me know if there's anything else.

**Review by sweinstein22 — APPROVED** [review]
Looks great, thanks so much for the PR!

**Pull request merged**
