### PR TITLE
Suggest logging in when unauthenticated users get rate-limited

### PR DESCRIPTION
**Pull request by 46bit**
## Short explanation of the proposed change:

This commit changes Cloud Controller's rate limiting middleware to suggest that unauthenticated users log in.

## Explanation of the use cases your change solves

This change helps users navigate the rate limits themselves rather than getting stuck and needing support. Without this change we've seen an awkward series of events:

1. A user was running something periodically against Cloud Controller;
2. They suspended their laptop overnight;
3. The next morning their login session had expired;
4. They hit our unauthenticated rate limit;
5. Other users on the same IP address got errors from `cf` that they did not know how to solve:
     ```
     Unexpected Response
     Response code: 429
     CC code:       10013
     CC error code: CF-RateLimitExceeded
     Request ID:    9cd9b261-9e4b-44d9-6edc-50ecee164f60::d3aeee04-32aa-4cb8-8d12-4ae2a19d4e11
     Description:   Rate Limit Exceeded
     ```
6. Those users came to us confused;
7. We eventually figured out they were logged out or their own login session had expired, so they had hit the IP-based rate limit;
8. They ran `cf login` and all was fine.

If this PR is merged, the error message users got would be a little more helpful:

```
Unexpected Response
Response code: 429
CC code:       10014
CC error code: CF-IPBasedRateLimitExceeded
Request ID:    9cd9b261-9e4b-44d9-6edc-50ecee164f60::d3aeee04-32aa-4cb8-8d12-4ae2a19d4e11
Description:   Rate Limit Exceeded: please log in again
```

That message prompts users to log in again, and suggests the rate limit is IP-based, giving them ways to solve their own issue. Without this change we wouldn't feel confident setting a low unauthenticated rate limit.

## Tickboxes

* [x] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/CONTRIBUTING.md)

* [x] I have viewed, signed, and submitted the Contributor License Agreement

* [x] I have made this pull request to the `master` branch

* [ ] I have run all the unit tests using `bundle exec rake`

* [ ] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng#cf-acceptance-tests-cats)

### CODE REVIEW

**Comment by tcdowney** [comment]
Thanks for submitting this PR, @46bit! I can see how the inability to distinguish between the unauthenticated IP-based rate limiting and the individual user token-based rate limiting could be confusing and think this could help improve that UX.

@ssisil do you have any thoughts/concerns about this or suggestions for the error message?

**Comment by ssisil** [comment]
Looks like a good UX improvement. 👍

**Comment by tcdowney** [comment]
@46bit was there a reason you have this as a draft still or would you like for us to start reviewing it?

**Comment by 46bit** [comment]
Thanks @tcdowney :) I was having trouble running some of the tests locally, and then got distracted. I'll fix the things that Codeclimate has highlighted tomorrow and move it into Ready for review :)

**Comment by 46bit** [comment]
@tcdowney @ssisil This is ready for review now :-) `bundle exec rake` is passing, but I don't have the CF Acceptance Tests set up to test it further.

**Comment by tcdowney** [comment]
Thanks again @46bit, I tested this out a bit locally and it looks good. Gonna merge it soon.

> That message prompts users to log in again, and suggests the rate limit is IP-based, giving them ways to solve their own issue.

Just to make it really clear for end users, I'm going to put out a quick follow up commit to tweak the message slightly to be: `Rate Limit Exceeded: Unauthenticated requests from this IP address have exceeded the limit. Please log in.`

**Comment by 46bit** [comment]
@tcdowney Wonderful, thanks for the review. And that's a great rewording.

**Comment by tcdowney** [comment]
Thank you for taking the time to submit this PR!

**Pull request merged**
