### PR TITLE
Space supporter unauthorized droplet endpoints

### LINKED ISSUE #2403: Ensure space supporter receives proper error code for specific droplet endpoints
## Context

We are introducing a [new role](https://github.com/cloudfoundry/cfar-proposals/issues/22) and we want to make sure it has the right access.

## Expected result

A space should get a 403 unauthorized error when trying to curl the following endpoints:

PATCH /v3/droplets/:guid
DELETE /v3/droplets/:guid
POST /v3/droplets
POST /v3/droplets?source_guid=:guid
GET /v3/droplets/:guid/download
POST /v3/droplets/:guid/upload

## Acceptance
As a space supporter, if I curl the above endpoints for a droplet that exists, I receive a 403 error telling me I am not authorized to perform this action.

## Documentation
No changes required. We are just aligning with our style guide.

### PR DESCRIPTION
**Pull request by moleske**
Thanks for contributing to cloud_controller_ng. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:
closes #2403 
* An explanation of the use cases your change solves

* Links to any other associated PRs

* [x] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/CONTRIBUTING.md)

* [x] I have viewed, signed, and submitted the Contributor License Agreement

* [x] I have made this pull request to the `main` branch

* [x] I have run all the unit tests using `bundle exec rake`

* [ ] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng#cf-acceptance-tests-cats)

### CODE REVIEW

**Review by monamohebbi — CHANGES_REQUESTED** [review]
We should be returning a 302 in the download droplet case still. Sorry for the delayed response. See [this comment](https://github.com/cloudfoundry/cloud_controller_ng/issues/2403#issuecomment-885963967) for more details

**Comment by weymanf** [comment]
> We should be returning a 302 in the download droplet case still. Sorry for the delayed response. See [this comment](https://github.com/cloudfoundry/cloud_controller_ng/issues/2403#issuecomment-885963967) for more details

The linked comment for the issue says to return a 403? But you're saying to return a 302 here?

**Comment by monamohebbi** [comment]
@weymanf - thanks for catching that! I meant 403 like in the comment.

**Review by sweinstein22 — CHANGES_REQUESTED** [review]
### Code Check

Looks good, thanks for catching that some of the rspec describes weren't quite right!

### Docs Check

Confirmed that the current state of the docs for all endpoints do not indicate that Space Supporters have access to them.

Looks like we've put in that [Space Supporters have access to `GET /v3/droplets/:guid/download`](https://github.com/cloudfoundry/cloud_controller_ng/pull/2428/files#diff-8ae2b238e2f1e7e669ff4beccf364c246a22a73ff9a686206027af9c8c321d23R46), which shouldn't be the case per the associated issue. Seems like we got it right in the specs, just not in the docs.

Otherwise looks good, thanks for adding in the description for Build State Updaters!

**Review by sweinstein22 — APPROVED** [review]
I went ahead and made the docs change as it was a minor one, as long as this PR passes the behavior check from Mona it should be good to go, thanks!

**Comment by monamohebbi** [comment]
### Upload droplet:

curl "https://api.stream-dart.capi.land/v3/droplets/a9e25595-7602-4e79-a30a-1b32210f0d7c/upload" -k  -X POST   -H "Authorization: bearer [token]"   -F bits=@"/tmp/droplet.tgz"
{
  "errors": [
    {
      "detail": "You are not authorized to perform the requested action",
      "title": "CF-NotAuthorized",
      "code": 10003
    }
  ]
}

### Download droplet
GET /v3/droplets/:guid/download
{
  "errors": [
    {
      "code": 10003,
      "detail": "You are not authorized to perform the requested action",
      "title": "CF-NotAuthorized"
    }
  ]
}

LGTM!

**Review by monamohebbi — APPROVED** [review]
### Upload droplet:

`curl "https://api.stream-dart.capi.land/v3/droplets/a9e25595-7602-4e79-a30a-1b32210f0d7c/upload" -k  -X POST   -H "Authorization: bearer [token]"   -F bits=@"/tmp/droplet.tgz"`
```
{
  "errors": [
    {
      "detail": "You are not authorized to perform the requested action",
      "title": "CF-NotAuthorized",
      "code": 10003
    }
  ]
}
```

### Download droplet
```
GET /v3/droplets/:guid/download
{
  "errors": [
    {
      "code": 10003,
      "detail": "You are not authorized to perform the requested action",
      "title": "CF-NotAuthorized"
    }
  ]
}
```

LGTM!

**Pull request merged**
