### PR TITLE
[WIP] Ruby 3 upgrade

### PR DESCRIPTION
**Pull request by sethboyles**
Working on Ruby 3 upgrade.

Biggest issue so far was changing keyword args: https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/ 

There is the [https://github.com/ruby/ruby2_keywords](https://github.com/ruby/ruby2_keywords) gem, but we figured we would try to adapt to the new, stricter usage first.  If it's too risky, we can try the gem instead

What needs to be done before this is good to go:

- [x] https://github.com/cloudfoundry/cloud_controller_ng/issues/2197 
- [x] https://github.com/fog/fog-google/pull/422 is merged and released
- [x] https://github.com/cloudfoundry/cf-uaa-lib/pull/73 is merged and consumed, preferably in a release rather than pointing at master or a specific branch
- [x] Either have this issue addressed in fog-local, or account for it on our end https://github.com/fog/fog-local/issues/24 
     - [x] (update: PR here: https://github.com/fog/fog-local/pull/25 )
     - [x] merged in and bumped in this branch 
- [ ] Update resources listed here: [Updating-Ruby-Package-in-CAPI-Release](https://github.com/cloudfoundry/cloud_controller_ng/wiki/Updating-Ruby-Package-in-CAPI-Release) 
     - [x] Update capi-release with a PR
     - [x] Updating the capi-migration-compatibility dockerfile
     - [ ] Updating Capi-workspace [non-blocking]
     - [x] Updating capi-runtime-ci dockerfile
     - [x] Updating the capi-ruby-units dockerfile

If the first 3 are done, and ruby 2.7 tests are passing, I think might be able to ahead and merge, and update the package in capi-release after.  But it's probably best to have these ready to go at the same time.

We are unsure if the unit tests have adequate coverage of the different fog gems (e.g fog-aliyun, fog-google, etc).  We have run into a few issue where we were using old versions of the fog gems that were using the now removed [URI.escape](https://docs.knapsackpro.com/2020/uri-escape-is-obsolete-percent-encoding-your-query-string).  We are wondering if might run into similar errors when running CATS and BARAS against these providers.

### CODE REVIEW

**Comment by sethboyles** [comment]
I think something about the Sinatra upgrade (2.0 -> 2.1) is causing some tests to fail:

```
 2) Sinatra::VCAP accessing a route that throws a low level exception should return json content type in the header
     Failure/Error: Unable to find /foo to read failed line

     ZeroDivisionError:
       divided by 0
     Shared Example Group: "http header content type" called from ./spec/unit/lib/sinatra/vcap_spec.rb:108
     # /foo:1
     # /bar:2
```

Our test calls this endpoint:
https://github.com/cloudfoundry/cloud_controller_ng/blob/main/spec/unit/lib/sinatra/vcap_spec.rb#L27-L32

Which divides by zero, and the expectation is that Sinatra returns a 500.  Looking at the Sinatra changelog, I'm not sure why this behavior would have changed...

**Comment by sethboyles** [comment]
Reason for divide by 0 issues: https://github.com/sinatra/sinatra/pull/1214.  

[spec/unit/lib/sinatra/vcap_spec.rb#19 ](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/spec/unit/lib/sinatra/vcap_spec.rb#L19-L21)

doesn't override helpers anymore

**Comment by sethboyles** [comment]
Due to another fog issue, we ended up pinning fog-google to `1.7.1`.  I am not sure that version is compatible with Ruby 3, so we may need to help https://github.com/fog/fog-google/pull/422 move forward so we can move to the newest version of fog-google.

**Comment by sethboyles** [comment]
This has suddenly been made more pressing, as Ruby 3 (3.1?) is required for the new Jammy Jellyfish stemcells: https://bosh.io/docs/jammy-migration/#openssl-3

**Comment by tjvman** [comment]
Closing, superseded by #2703

**Pull request closed without merging**
