### PR TITLE
Add audit events for organizations

### PR DESCRIPTION
**Pull request by ScarletTanager**
PR for [this issue](https://github.com/cloudfoundry/cloud_controller_ng/issues/758).

### CODE REVIEW

**Comment by aashah** [comment]
Hey @ScarletTanager,

The timing of this PR unfortunately coincided with a refactor for event repositories (story: https://www.pivotaltracker.com/story/show/130534889). The purpose was to extract user audit info away from the event repositories as we needed to extend them, and having to change every method on every event repository was tedious.

We'd like to see the same refactors for the `OrganizationEventRepository` introduced in this PR.

Thanks,
CAPI Community Pair - @aashah & @jberkhahn

**Comment by ScarletTanager** [comment]
@aashah @jberkhahn Sure thing, will do.

**Comment by ScarletTanager** [comment]
@aashah @jberkhahn I did the refactor, take a look?

**Comment by aashah** [comment]
I did merge this in manually due to the api_version_spec test. Closing manually as well.

See commits:

> 501765882ec28566ede49d2d126beb2f55d4b1dd
> 832a9a73db2a5265114e7c53c4129dfe0548be52

**Pull request closed without merging**
