### PR TITLE
Select from a larger pool of stagers if needed

### PR DESCRIPTION
**Pull request by fraenkel**
As the number of potential DEA stagers grow, allow the pool to grow as well.

### CODE REVIEW

**Comment by fraenkel** [comment]
One way to solve issue #419

**Comment by zrob** [comment]
@fraenkel this seems pretty solid.   We were thinking we go with minimum of 5, make the percentage configurable with a default of the 1% you have now.   

We'll pull it in if you can add some tests and the configurability change.

@dieucao do you have a preference for the manifest property for the percentage?

**Comment by dieucao** [comment]
How about `placement_top_stager_percentage` ? It's 4 words though...

**Comment by fraenkel** [comment]
Just updated the code. I don't have a fast internet so I cannot test the BOSH changes in cf-release yet.

**Comment by wendorf** [comment]
Hi @fraenkel ,

Looks good! We just merged it and will bump cf-release to have the change.

Thanks,
@wendorf and @jberkhahn , Cloud Foundry CAPI team

**Pull request merged**
