### PR TITLE
add fog-aliyun for cloud foundry deployment

### PR DESCRIPTION
**Pull request by xiaozhu36**
Thanks for contributing to cloud_controller_ng. To speed up the process of reviewing your pull request please provide us with:

* This PR adds fog-aliyun and aims to use it to deploy Cloud Foundry.

* [x] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/CONTRIBUTING.md)

* [x] I have viewed, signed, and submitted the Contributor License Agreement

* [x] I have made this pull request to the `master` branch

* [ ] I have run all the unit tests using `bundle exec rake`

* [ ] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng#cf-acceptance-tests-cats)

### CODE REVIEW

**Comment by zrob** [comment]
@petergtz @smoser-ibm 

I'm not sure what to do in the context of the new golang bits service.  In the fog compatible world I would normally just accept this..

**Comment by petergtz** [comment]
@zrob I think it's fine to merge it. Even if Bits-Service were still written in Ruby, merging this PR wouldn't automatically make Bits-Service support Alibaba Cloud. The fact that Bits-Service does not support it, shouldn't be a stopper for Cloud Controller.

We have [a story to add support in Bits-Service](https://www.pivotaltracker.com/story/show/157928837).

**Comment by tcdowney** [comment]
Hello @xiaozhu36!

We noticed you dropped by in our Slack channel  a few days ago and it sounded like you were having trouble validating that the Cloud Controller works successfully with [Alibaba Cloud OSS](https://www.alibabacloud.com/product/oss?spm=a3c0i.7911826.1097638.dnavproductsb1.4419737bA7L4Sc).

Slack Convo:
https://cloudfoundry.slack.com/archives/C07C04W4Q/p1528939029000169

Did you get it working? If so, we can merge it, but we'd like it if you marked it as experimental in the README (since our team does not test this integration directly).

Also, can you squash your commits and rebase this branch against the latest code on `master`? Thanks!

@ewrenn8 && Tim

**Comment by xiaozhu36** [comment]
Hi @tcdowney I have found the reason about problem in Slack channel and the reason is I used an incorrect way to install wordpress and it is not related the fog-aliyun. I can push other application using  Alibaba Cloud fog. So, you can merge it.

In addition, I have rebase this branch on master, please check it.

By the way, what is the mean of  "marked it as experimental in the README "?

Regards,
Guimin He

**Comment by ewrenn8** [comment]
We can take care of the README.

Thanks!

Eli && @lisamcho

**Pull request merged**
