### PR TITLE
Adds permissions tests for V3 users

### LINKED ISSUE #2401: Ensure space supporter receives proper error code for specific user endpoints
## Context

We are introducing a [new role](https://github.com/cloudfoundry/cfar-proposals/issues/22) and we want to make sure it has the right access.

## Expected result

A space should get a 403 unauthorized error when trying to curl the following endpoints:

DELETE /v3/users/:guid
PATCH /v3/users/:guid

## Acceptance
As a space supporter, if I curl the above endpoints for a user that exists, I receive a 403 error telling me I am not authorized to perform this action.

## Documentation
No changes required. We are just aligning with our style guide.

### PR DESCRIPTION
**Pull request by galenhammond**
We initially intended to give space supporters a 403 instead of a 404,
however it seems space supporters should indeed get a 404

Closes #2401

Co-authored-by: Matthew Kocher <mkocher@pivotal.io>
Co-authored-by: Galen Hammond <galenh@vmware.com>

* [x] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/CONTRIBUTING.md)

* [x] I have viewed, signed, and submitted the Contributor License Agreement

* [x] I have made this pull request to the `main` branch

* [x] I have run all the unit tests using `bundle exec rake`

* [ ] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng#cf-acceptance-tests-cats)

### CODE REVIEW

**Review by sweinstein22 — COMMENTED** [review]
## Acceptance

### Behavior Check

Interestingly I still seem to be getting `403`s, although the tests look like this should be working correctly. It's possible I've got something wrong on my end, do you all mind having another look? Potentially worth noting I merged in main before deploying these changes. @galenhammond @mkocher 

```
$ cf curl -X DELETE /v3/users/c3a7d5fd-e90f-47f9-bd87-8063f6119999 -v
REQUEST: [2021-07-16T14:50:40-07:00]
DELETE /v3/users/c3a7d5fd-e90f-47f9-bd87-8063f6119999 HTTP/1.1
...

RESPONSE: [2021-07-16T14:50:40-07:00]
HTTP/1.1 403 Forbidden
...
{
  "errors": [
    {
      "code": 10003,
      "detail": "You are not authorized to perform the requested action",
      "title": "CF-NotAuthorized"
    }
  ]
}
$ cf curl -X PATCH /v3/users/c3a7d5fd-e90f-47f9-bd87-8063f6119999 -v
REQUEST: [2021-07-16T14:51:35-07:00]
PATCH /v3/users/c3a7d5fd-e90f-47f9-bd87-8063f6119999 HTTP/1.1
...

RESPONSE: [2021-07-16T14:51:36-07:00]
HTTP/1.1 403 Forbidden
...
{
  "errors": [
    {
      "code": 10003,
      "detail": "You are not authorized to perform the requested action",
      "title": "CF-NotAuthorized"
    }
  ]
}
```

**Comment by monamohebbi** [comment]
Also @mkocher @galenhammond - why did you all opt for 404 over 403's? I assumed they should get 403's since they have read permissions as of this [pr](https://github.com/cloudfoundry/cloud_controller_ng/pull/2317)

**Comment by mkocher** [comment]
From looking at the code user viewing seems to be based on org membership and not space membership. I'm not sure how org membership works in real life with a space role and if it might be different than how the tests set it up. I'll take a look.

**Comment by mkocher** [comment]
Updated the specs to include space_supporter. We had been a little confused by there being two users (current user and the user being edited/deleted). Didn't update the controller as all user code is based on org membership so doesn't change for space_supporters vs any other space role.

**Review by monamohebbi — CHANGES_REQUESTED** [review]
It looks like the confusion is permission logic for the users endpoints will change depending on your users affiliation to different orgs and spaces. The two `PATCH` tests you all updated cover the expected [403](https://github.com/cloudfoundry/cloud_controller_ng/blob/328e03c2d7893feadbbbff645d6d345ef603a74a/spec/request/users_spec.rb#L859-L862) and [404](https://github.com/cloudfoundry/cloud_controller_ng/blob/328e03c2d7893feadbbbff645d6d345ef603a74a/spec/request/users_spec.rb#L837-L840) cases.

This would explain Sarah getting the 403s still because she was probably testing as a user affiliated with the space/org.

The only change I'd still request is if you could update the delete [tests](https://github.com/cloudfoundry/cloud_controller_ng/blob/328e03c2d7893feadbbbff645d6d345ef603a74a/spec/request/users_spec.rb#L929) to include the space supporter as well and ensure the bake still passes.

**Comment by mariash** [comment]
@monamohebbi we updated the tests to include space supporter.

**Comment by monamohebbi** [comment]
### Behavior Check

#### Setup 403
Logged in as a supporter user and confirmed I could see all but user otherorg_supporter. Grabbed guid for a user affiliated with the supporters organization. 

Running
` cf curl -X DELETE /v3/users/:guid`
returned 
```
{
   "errors": [
      {
         "detail": "You are not authorized to perform the requested action",
         "title": "CF-NotAuthorized",
         "code": 10003
      }
   ]
}
```

Running
` cf curl -X PATCH /v3/users/:guid`
returned 
```
{
   "errors": [
      {
         "detail": "You are not authorized to perform the requested action",
         "title": "CF-NotAuthorized",
         "code": 10003
      }
   ]
}
```

#### Setup 404
Logged in as otherorg_supporter and confirmed that listing the users only returned users in org otherorg. I used the same guid from above (a user good not affiliated with other org).

Running
` cf curl -X DELETE /v3/users/:guid`
returned 
```
{
   "errors": [
      {
         "detail": "User not found",
         "title": "CF-ResourceNotFound",
         "code": 10010
      }
   ]
}
```

Running
` cf curl -X PATCH /v3/users/:guid`
returned 
```
{
   "errors": [
      {
         "detail": "User not found",
         "title": "CF-ResourceNotFound",
         "code": 10010
      }
   ]
}
```

Looks good to me!

**Review by monamohebbi — APPROVED** [review]
### Behavior Check

#### Setup 403
Logged in as a supporter user and confirmed I could see all but user otherorg_supporter. Grabbed guid for a user affiliated with the supporters organization. 

Running
` cf curl -X DELETE /v3/users/:guid`
returned 
```
{
   "errors": [
      {
         "detail": "You are not authorized to perform the requested action",
         "title": "CF-NotAuthorized",
         "code": 10003
      }
   ]
}
```

Running
` cf curl -X PATCH /v3/users/:guid`
returned 
```
{
   "errors": [
      {
         "detail": "You are not authorized to perform the requested action",
         "title": "CF-NotAuthorized",
         "code": 10003
      }
   ]
}
```

#### Setup 404
Logged in as otherorg_supporter and confirmed that listing the users only returned users in org otherorg. I used the same guid from above (a user good not affiliated with other org).

Running
` cf curl -X DELETE /v3/users/:guid`
returned 
```
{
   "errors": [
      {
         "detail": "User not found",
         "title": "CF-ResourceNotFound",
         "code": 10010
      }
   ]
}
```

Running
` cf curl -X PATCH /v3/users/:guid`
returned 
```
{
   "errors": [
      {
         "detail": "User not found",
         "title": "CF-ResourceNotFound",
         "code": 10010
      }
   ]
}
```

Looks good to me!

**Review by sweinstein22 — APPROVED** [review]
### Code Check

Looks good, thanks for shifting around the describes so they make more sense!

### Docs Check

Confirmed that docs don't currently indicate that Space Supporter has access to them. Interestingly I think we have an issue in the docs currently - [update a user](https://v3-apidocs.cloudfoundry.org/version/3.101.0/index.html#update-a-user) says it's `PATCH /v3/users` rather than `PATCH /v3/users/:guid`. I'll plan to make that change separately from this PR.

**Pull request merged**
