### PR TITLE
Allow space application supporter to access specific domain endpoints

### LINKED ISSUE #2219: Allow space application supporter to access specific domain endpoints.
## Issue

Allow space application supporter to access specific **domain** endpoints. 

## Context

We are introducing a [new role](https://github.com/cloudfoundry/cfar-proposals/issues/22) and we want to make sure it has the right access.

## Expected result
A space application support should be able access the following endpoints:

GET /v3/domains/:guid
GET /v3/domains
GET /v3/organizations/:guid/domains

## Acceptance
A space application supporter would see the same info as a space developer assigned to the same space for these and only these domain endpoints.

## Documentation
When I browse to any of these endpoints on [v3 docs](https://v3-apidocs.cloudfoundry.org/version/3.99.0/index.html) I can see the Space Application Supporter role in the list of permitted roles with an indication that this role is not fully implemented and the permissions will be changing.

### PR DESCRIPTION
**Pull request by philippthun**
Closes #2219

* [x] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/CONTRIBUTING.md)

* [x] I have viewed, signed, and submitted the Contributor License Agreement

* [x] I have made this pull request to the `main` branch

* [x] I have run all the unit tests using `bundle exec rake`

* [ ] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng#cf-acceptance-tests-cats)

### CODE REVIEW

**Comment by sweinstein22** [comment]
## Acceptance

Confirmed user only has space_application_supporter and organization_user roles:

```
$ cf curl /v3/roles?user_guids="d8685663-a98a-4c4d-86b0-4523dd45a8b1"
{
  ...
  "resources": [
    {
      "guid": "29ab067c-7205-4fe4-be13-bd63009fcc2a",
      "type": "space_application_supporter",
      "relationships": {
        "user": {
          "data": {
            "guid": "d8685663-a98a-4c4d-86b0-4523dd45a8b1"
          }
        },
      ...
    },
    {
      "guid": "f079f79a-81d9-4ec1-8229-051ddafc3c72",
      "type": "organization_user",
      "relationships": {
        "user": {
          "data": {
            "guid": "d8685663-a98a-4c4d-86b0-4523dd45a8b1"
          }
        },
      ...
    }
  ]
}
```

Ran `cf curl` against `/v3/domains/:guid`, `/v3/domains`, and `/v3/organizations/:guid/domains` as user and as a space developer, piped results to files

Confirmed that output of calls matched by checking for empty diff:
```
$ diff space_dev_domains space_app_supporter_domains

$ diff space_dev_domains_guid space_app_supporter_domains_guid

$ diff space_dev_org_guid_domains space_app_supporter_org_guid_domains
```

### Code Review:
Checked that `readable_org_guids_for_domains` is only being used in cases where the space_application_supporter role has been introduced, allowing us to remove the conditional statement
 - In doing so we're also changing permissions for the `GET /v3/organizations/:guid/domains/default` endpoint.
    - It looks like this was originally intended to be included in [this github issue](https://github.com/cloudfoundry/cloud_controller_ng/issues/2223), but given the work is already done in this PR I think it makes sense to include it here.

    - As the code change has already been implemented, the output between a space_application_supporter and a space_developer are already the same:
    ```
    $ diff space_dev_org_guid_domains_default space_app_supporter_org_guid_domains_default
   
     ```
    - The request spec for this endpoint has also been adjusted accordingly, but it looks like the documentation for the endpoint has not been updated.

Examined the request spec changes, looks like we've a specs around the `GET /v3/organizations/:guid/usage_summary` endpoint indicating they should receive a `200`, which is not included in this this issue.
  - Confirmed the output between a space_application_supporter and a space_developer are the same:
    ```
    diff space_dev_org_usage_summary space_app_supporter_org_usage_summary
    
    ```
  - Checked the docs and it's indicated as visible to All Roles, no further changes required
  - Similar to the default domain endpoint, it looks like it was slated to be addressed in [this github issue](https://github.com/cloudfoundry/cloud_controller_ng/issues/2223). I'll make note in that issue to indicate that the two endpoints have been addressed in this PR as the request spec has already been changed.

Checked that `find_domain` is only being used in cases where the space_application_supporter role has been introduced, allowing us to remove the conditional statement
- While `find_domain` is used in other endpoints that the space_application_supporter won't have access to, they're all guarded by checks for write permissions

**Review by sweinstein22 — CHANGES_REQUESTED** [review]
### Changes Requested:
- Add documentation to `GET /v3/organizations/:guid/domains/default` indicating that the Space Application Supporter role has access to the endpoint

**Comment by philippthun** [comment]
@sweinstein22 Thanks for reviewing the PR. I've added the missing documentation.

**Review by sweinstein22 — APPROVED** [review]
Perfect, thanks @philippthun !

**Pull request merged**
