### PR TITLE
Space application supporter can get and list packages

### LINKED ISSUE #2225: Allow space application supporter to access specific packages endpoints.
## Issue

Allow space application supporter to access specific **packages** endpoints. 

## Context

We are introducing a [new role](https://github.com/cloudfoundry/cfar-proposals/issues/22) and we want to make sure it has the right access.

## Expected result
A space application support should be able access the following endpoints:

GET /v3/packages/:guid
GET /v3/apps/:guid/packages

## Acceptance
A space application supporter would see the same info as a space developer assigned to the same space for these and only these packages endpoints.

## Documentation
When I browse to any of these endpoints on [v3 docs](https://v3-apidocs.cloudfoundry.org/version/3.99.0/index.html) I can see the Space Application Supporter role in the list of permitted roles with an indication that this role is not fully implemented and the permissions will be changing.

### PR DESCRIPTION
**Pull request by will-gant**
* Enable space application supporter to get and list packages (including [listing them as a subresource of apps](https://v3-apidocs.cloudfoundry.org/version/3.101.0/index.html#list-packages-for-an-app)).
* Add unit tests to prove the above

Closes #2225 

* [x] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/CONTRIBUTING.md)

* [x] I have viewed, signed, and submitted the Contributor License Agreement

* [x] I have made this pull request to the `main` branch

* [x] I have run all the unit tests using `bundle exec rake`

* [ ] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng#cf-acceptance-tests-cats)

### CODE REVIEW

**Comment by sweinstein22** [comment]
Hi @will-gant, Rubocop is failing on this PR with the following error:
```
spec/request/packages_spec.rb:403:9: W: Lint/UselessAssignment: Useless assignment to variable - bits_package.
```

**Review by monamohebbi — APPROVED** [review]

**Review by monamohebbi — CHANGES_REQUESTED** [review]
Please fix the following style changes:
```
spec/request/packages_spec.rb:403:9:  Lint/UselessAssignment: Useless assignment to variable - bits_package. Did you mean bits_type?
        bits_package = VCAP::CloudController::PackageModel.make(type: bits_type, app_guid: app_model.guid)
spec/request/packages_spec.rb:425:1: Layout/EmptyLinesAroundBlockBody: Extra empty line detected at block body end.
spec/request/packages_spec.rb:425:1:  Layout/TrailingWhitespace: Trailing whitespace detected.
```

**Comment by will-gant** [comment]
Unit tests now pass :)

I've also fixed the rubocop issues. Many thanks for your patience - these are pretty much the first code changes I've PR'd to an open source project!

**Comment by monamohebbi** [comment]
Thanks @will-gant! @sweinstein22 see my earlier comment to find the environment and users for testing.

**Comment by sweinstein22** [comment]
### Behavior check

Ran `cf curl` against `GET /v3/packages/:guid`, `GET /v3/packages`, and `GET /v3/apps/:guid/packages` as a space application supporter and space developer, confirmed that there was was no diff and manually checked output. 

### Code review

Implementation looks good. Some adjustments to the request spec changes would bring the spec more inline with the patterns we've been trying to convert to as part of the introduction of this role. 

### Docs

Minor alphabetization would bring the changes introduced more inline with the patterns of the docs

**Review by sweinstein22 — CHANGES_REQUESTED** [review]
### Requested changes to `spec/request/packages_spec.rb`

As part of this effort we've been trying to unify the permissions testing structure in our request specs, so it would be nice to convert the specs impacted in this PR to the shared examples structure.

In practice, this would mean shifting the `context 'as a space application supporter'` and `context 'as a space developer'` for `/v3/packages` and `/v3/apps/:guid/packages` into a shared example that leverages the `it_behaves_like 'permissions for list endpoint'` shared example. For `/v3/packages/:guid` it would mean shifting to `it_behaves_like 'permissions for single object endpoint'`. Examples for both of these patterns can be seen in the request spec for app. ([list endpoint](https://github.com/cloudfoundry/cloud_controller_ng/blob/aeba231e4005af5f4782db80020d7b69f0973134/spec/request/apps_spec.rb#L433-L555), [single object endpoint](https://github.com/cloudfoundry/cloud_controller_ng/blob/aeba231e4005af5f4782db80020d7b69f0973134/spec/request/apps_spec.rb#L1343-L1390))

A lot of the heavy lifting for such a change is in place - an expected response is already present for the [app level package request](https://github.com/cloudfoundry/cloud_controller_ng/blob/a6064cd72a31b7141b97c2791d67de1c604b386e/spec/request/packages_spec.rb#L175), the [package list request](https://github.com/cloudfoundry/cloud_controller_ng/blob/a6064cd72a31b7141b97c2791d67de1c604b386e/spec/request/packages_spec.rb#L445), and the [request for a specific package](https://github.com/cloudfoundry/cloud_controller_ng/blob/a6064cd72a31b7141b97c2791d67de1c604b386e/spec/request/packages_spec.rb#L712) tests.

It's also worth noting that these shared examples are dependent on having an org and space defined as named variables in the spec, similar to the [top level definitions found in the app request spec](https://github.com/cloudfoundry/cloud_controller_ng/blob/aeba231e4005af5f4782db80020d7b69f0973134/spec/request/apps_spec.rb#L9-L10). The packages request spec already has a top level space defined but not an org.

I know this is a lot to explain over a comment, feel free to follow up if you have any questions!

### Docs

Minor/nitpicky request, but we've been alphabetizing the roles in the docs. If we could move the Space Application Supporter row to be at the top of the space roles that would be great.

**Comment by will-gant** [comment]
@sweinstein22 Thanks for all the thought and effort you put into explaining that to me. You're right - the approach you outline is definitely better. I've just pushed my attempt at implementing your suggestions. Please let me know if there's anything I've missed!

**Comment by sweinstein22** [comment]
Great, thanks so much for making the adjustments @will-gant ! One last minor thing and then it should be ready to be merged in - Rubocop is failing with the following error:
```
spec/request/packages_spec.rb:459:52: C: [Correctable] Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
      let(:api_call) { lambda { |user_headers| get "/v3/packages", { per_page: per_page }, user_headers } }
```

**Comment by will-gant** [comment]
Fixed. I'll try to remember to repeat that after each new commit on my next PR! Thanks again.

**Review by sweinstein22 — APPROVED** [review]

**Pull request merged**
