### PR TITLE
Default value configurable for app ssh access on new applications

### PR DESCRIPTION
**Pull request by tyyko**
Refers to: #735

* A short explanation of the proposed change:
When ssh access is allowed by the operator, it is enabled by default for all apps and spaces and an action from space owner or developers is required to locally disable it.

It would make sense to allow the configuration of the default setting and not having it hardcoded to true.

* An explanation of the use cases your change solves
On productive deployments, especially when migrating from DEA to to Diego, it would make sense to allow the operator to deploy Diego with the ssh service as 'opt-in' feature where developers can activate the feature but by default we don't open any channel that can lead to security concerns.

* [x] I have viewed signed and have submitted the Contributor License Agreement

* [x] I have made this pull request to the `master` branch

* [x] I have run all the unit tests using `bundle exec rake`

* [x] I have run CF Acceptance Tests on bosh lite

I still have to run CATs, will do as soon as possible.

### CODE REVIEW

**Comment by tyyko** [comment]
I confirm CATS behave exactly the same with upstream version and with my fix applied

**Comment by aashah** [comment]
Hey @tyyko,

Everything looks good. We have one small request, we have been trying to prevent copy/pasta'ing properties over to the clock and worker templates as many of them are not relevant for those jobs. In this case, we believe that this property is not relevant for the clock. Could you please update the PR to remove the property being sent into the clock job's template (see `bosh/jobs/cloud_controller_clock/templates/cloud_controller_clock.yml.erb`)

Thanks,
CAPI Community Pair - @michaelxupiv & @aashah

**Comment by tyyko** [comment]
Hello @michaelxupiv & @aashah,

Thanks for your feedback!
I just removed the changes to the clock job.

Best,
Michael

**Comment by tyyko** [comment]
Hello, are there any other issues about the PR? 

Thanks,
Michael

**Comment by simonleung8** [comment]
@tyyko Sorry for the delay. We had issues with our CI and it was blocking us from merging this PR.

It is merged now. Thanks

**Pull request merged**
