### PR TITLE
Use Azue storage to store blobs

### PR DESCRIPTION
**Pull request by AbelHu**
* A short explanation of the proposed change: Support to use Azure storage to store blobs

* An explanation of the use cases your change solves: This will help Azure CF users to discard NFS Server

* [x] I have viewed signed and have submitted the Contributor License Agreement

* [x] I have made this pull request to the `master` branch

* [x] I have run all the unit tests using `bundle exec rake`

* [ ] I have run CF Acceptance Tests on bosh lite

I have run `bundle exec rake` but got many errors as below. It seems like that this error is not caused by my change.

```
     Failure/Error: pid = Process.spawn(opts[:env], cmd, spawn_opts)

     Errno::ENOENT:
       No such file or directory - gnatsd
```

`bundle exec rake` result:
```
Randomized with seed 50925

.............................................................

Finished in 10 minutes 49 seconds (files took 36.85 seconds to load)
6623 examples, 0 failures

Randomized with seed 54843


11919 examples, 62 failures, 32 others
```

`bundle exec rspec spec/unit/*` result:

```
Finished in 17 minutes 29 seconds (files took 47.02 seconds to load)
11174 examples, 0 failures

Randomized with seed 44550
```

Configure to use Azure storage to store blob:
```
      fog_connection: &fog_connection
        provider: AzureRM
        environment: 'AzureCloud' or 'AzureChinaCloud' or 'AzureUSGovernment' or 'AzureGermanCloud'
        azure_storage_account_name: YOUR-AZURE-STORAGE-ACCOUNT-NAME
        azure_storage_access_key: YOUR-AZURE-STORAGE-ACCESS-KEY
```

### CODE REVIEW

**Comment by NingKuang** [comment]
Hi, @cf-gitbot , do you know when this request will be merged and released ? I hope to wrap this up before the Christmas holiday.  Thanks.

**Comment by Gerg** [comment]
Hey @AbelHu & @NingKuang,

There was a merge conflict in the Gemfile.lock, so I merged manually in this commit: https://github.com/cloudfoundry/cloud_controller_ng/commit/df3cd6a0128c0b4905e622011e2b1e1cf2868396

Thanks for your PR!

**Comment by SocalNick** [comment]
FYI - This has made it into the [OSS CF-250](https://github.com/cloudfoundry/cf-release/releases/tag/v250)

**Comment by AbelHu** [comment]
@Gerg , @SocalNick Thank you so much!

**Pull request closed without merging**
