### PR TITLE
Space supporter can get and update app environment variables

### LINKED ISSUE #2271: Space Application Supporter can access specific app environment variable endpoints
## Issue

Allow space application supporter to access specific app environment variable endpoints. 

## Context

We are introducing a [new role](https://github.com/cloudfoundry/cfar-proposals/issues/22) and we want to make sure it has the right access.

## Expected result
A space application support should be able access the following endpoints:

- [ ] GET /v3/apps/:guid/environment_variables
- [ ] PATCH /v3/apps/:guid/environment_variables

## Acceptance
A space application supporter would see the same info as a space developer assigned to the same space for these and only these endpoints.

## Documentation
When I browse to any of these endpoints on [v3 docs](https://v3-apidocs.cloudfoundry.org/version/3.99.0/index.html) I can see the Space Application Supporter role in the list of permitted roles with an indication that this role is not fully implemented and the permissions will be changing.

### PR DESCRIPTION
**Pull request by will-gant**
* Space supporter can get app environment variables via `/v3/apps/:guid/environment_variables` when `space_developer_env_var_visibility` is not disabled
* Space supporter can update app environment variables
* Space supporter can get app environment variables via `/v3/apps/:guid/env`, but system_env_json is redacted.
* Adds unit tests to prove that space supporters can get app environment variables via the above endpoints, but that they cannot when `space_developer_env_var_visibility` is disabled, and to prove that they can always update app environment variables.
* Updates docs for the `space_developer_env_var_visibility` flag.
* Fixes what I believe was a typo in `spec/support/user_helpers.rb`.

Closes #2271 and #2386

* [x] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/CONTRIBUTING.md)

* [x] I have viewed, signed, and submitted the Contributor License Agreement

* [x] I have made this pull request to the `main` branch

* [x] I have run all the unit tests using `bundle exec rake`

* [ ] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng#cf-acceptance-tests-cats)

### CODE REVIEW

**Comment by will-gant** [comment]
Just updated the docs for this, including those for the feature flag `space_developer_env_var_visibility`

**Comment by will-gant** [comment]
Setting this to a draft PR, as I've now started #2386 and there's a fair bit of overlap, so I think I'll use the same branch.

**Comment by will-gant** [comment]
The work on #2386 is done now, so I'll set this back to ready for review. Just to re-emphasise: this PR covers two user stories (also #2271) that both concern endpoints for application environment variables.

One query I would make is whether it might help avoid confusion if, rather than space supporters always seeing an empty object for system_env_json, such users instead saw a string saying the contents were hidden/redacted - as I see is done for some other endpoints. What do you think?

**Review by monamohebbi — CHANGES_REQUESTED** [review]
Thank you for bringing this to my attention! It looks like there is a [redacting function](https://github.com/cloudfoundry/cloud_controller_ng/blob/fddf001059bfd06deaf124dee59418f72c021e67/app/presenters/v3/base_presenter.rb#L18-L20) we can rely on to create similar and consistent behavior (maybe what you were already thinking about). I think given this, I'd prefer to show the redacted view. I'll edit the issue and still run through the basic behavior checks 

Edit:

unfortunately, this branch is facing the same nasty rebasing conflicts around the queryer being removed. Could you all rebase this as well while you are making those changes?

**Comment by iaftab-alam** [comment]
hey @monamohebbi,

Can you move out this draft, as it is ready and will is on holidays.

Regards,
Aftab

**Review by monamohebbi — APPROVED** [review]
### Setup 

Pushed app dora from cf-acceptance-tests repo. Added environment variables.

### Behavior Check
#### Env
**Running** `cf curl v3/apps/$(cf app dora --guid)/env` as supporter returns
```
{
   "environment_variables": {
      "env": "var"
   },
   "staging_env_json": {
      "foo": "bar"
   },
   "running_env_json": {
      "foo": "baz"
   },
   "system_env_json": {
      "redacted_message": "[PRIVATE DATA HIDDEN]"
   },
   "application_env_json": {
      "VCAP_APPLICATION": {
         "cf_api": "https://api.atom-mask.capi.land",
         "limits": {
            "fds": 16384
         },
         "application_name": "dora",
         "application_uris": [
            "dora.atom-mask.capi.land"
         ],
         "name": "dora",
         "space_name": "space",
         "space_id": "42fa2be4-9c30-4c0e-8b9c-0a68f4b9521a",
         "organization_id": "89844734-d1a2-4249-8db6-23beca6b9024",
         "organization_name": "org",
         "uris": [
            "dora.atom-mask.capi.land"
         ],
         "users": null,
         "application_id": "ac4d7097-7092-4ca3-a914-11c29fd424d8"
      }
   }
}
```
**Running** `cf curl v3/apps/$(cf app dora --guid)/env` as developer returns
```
{
   "environment_variables": {
      "env": "var"
   },
   "staging_env_json": {
      "foo": "bar"
   },
   "running_env_json": {
      "foo": "baz"
   },
   "system_env_json": {
      "redacted_message": "[PRIVATE DATA HIDDEN]"
   },
   "application_env_json": {
      "VCAP_APPLICATION": {
         "cf_api": "https://api.atom-mask.capi.land",
         "limits": {
            "fds": 16384
         },
         "application_name": "dora",
         "application_uris": [
            "dora.atom-mask.capi.land"
         ],
         "name": "dora",
         "space_name": "space",
         "space_id": "42fa2be4-9c30-4c0e-8b9c-0a68f4b9521a",
         "organization_id": "89844734-d1a2-4249-8db6-23beca6b9024",
         "organization_name": "org",
         "uris": [
            "dora.atom-mask.capi.land"
         ],
         "users": null,
         "application_id": "ac4d7097-7092-4ca3-a914-11c29fd424d8"
      }
   }
}
```

#### Environment Variables 
**Running** `cf curl v3/apps/$(cf app dora --guid)/environment_variables` as supporter returns
```
{
   "var": {
      "env": "var"
   },
   "links": {
      "self": {
         "href": "https://api.atom-mask.capi.land/v3/apps/ac4d7097-7092-4ca3-a914-11c29fd424d8/environment_variables"
      },
      "app": {
         "href": "https://api.atom-mask.capi.land/v3/apps/ac4d7097-7092-4ca3-a914-11c29fd424d8"
      }
   }
}
```

**Running** `cf curl v3/apps/$(cf app dora --guid)/environment_variables` returns
```
{
   "var": {
      "env": "var"
   },
   "links": {
      "self": {
         "href": "https://api.atom-mask.capi.land/v3/apps/ac4d7097-7092-4ca3-a914-11c29fd424d8/environment_variables"
      },
      "app": {
         "href": "https://api.atom-mask.capi.land/v3/apps/ac4d7097-7092-4ca3-a914-11c29fd424d8"
      }
   }
}
```
**Running** 
```
cf curl -X PATCH v3/apps/$(cf app dora --guid)/environment_variables -d '{
      "var": {
        "DEBUG": "false",
        "USER": null
      }
    }'
``` 
as supporter and developer returns
```
{
   "var": {
      "env": "var",
      "DEBUG": "false"
   },
   "links": {
      "self": {
         "href": "https://api.atom-mask.capi.land/v3/apps/ac4d7097-7092-4ca3-a914-11c29fd424d8/environment_variables"
      },
      "app": {
         "href": "https://api.atom-mask.capi.land/v3/apps/ac4d7097-7092-4ca3-a914-11c29fd424d8"
      }
   }
}
```

#### When flag is enabled
**SETUP** as admin:
```
cf curl -X PATCH v3/feature_flags/space_developer_env_var_visibility -d '{
    "enabled": false,
    "custom_error_message": "Env var visibility is obscured" }'
{
   "name": "space_developer_env_var_visibility",
   "enabled": false,
   "updated_at": "2021-07-22T18:34:16Z",
   "custom_error_message": "Env var visibility is obscured",
   "links": {
      "self": {
         "href": "https://api.atom-mask.capi.land/v3/feature_flags/space_developer_env_var_visibility"
      }
   }
}

```

**Running**  `cf curl v3/apps/$(cf app dora --guid)/env` returns
```
{
   "errors": [
      {
         "detail": "Feature Disabled: Env var visibility is obscured",
         "title": "CF-FeatureDisabled",
         "code": 330002
      }
   ]
}
```

**Running**  `cf curl v3/apps/$(cf app dora --guid)/environment_variables` returns
```
{
   "errors": [
      {
         "detail": "Feature Disabled: Env var visibility is obscured",
         "title": "CF-FeatureDisabled",
         "code": 330002
      }
   ]
}
```

LGTM! Thanks for the changes.

**Comment by sweinstein22** [comment]
Looks like we've got some failing unit tests, @iaftab-alam do you mind having a look when you have time?

**Comment by iaftab-alam** [comment]
hey @sweinstein22, sure I will check that.

Regards,
Aftab

**Comment by iaftab-alam** [comment]
hey @sweinstein22,

The unit tests are passing now. You can convert this draft into PR as I am not the author (will is on vacations) and can proceed further.

Regards,
Aftab

**Review by sweinstein22 — APPROVED** [review]
### Code Check

Looks good! Thanks for using the request spec shared examples and helper functions we've established for this track of work, and for taking the time to clarify the describes (especially around redacted/non-redacted components)

### Docs Check

Confirmed that all three endpoints indicate that they can be accessed by space supporters, and that they include an experimental note. Thanks for also taking the time to change the wording of the longer descriptions to indicate how space supports play into the space developer env var visibility flag!

**Pull request merged**
