### PR TITLE
Use the branch "fog-arm-cf" of fog-azure-rm

### PR DESCRIPTION
**Pull request by bingosummer**
Thanks for contributing to cloud_controller_ng. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:
Use the branch `fog-arm-cf` of fog-azure-rm to support Azure Stack storage

* An explanation of the use cases your change solves
https://github.com/fog/fog-azure-rm/issues/367

* Links to any other associated PRs

* [x] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/CONTRIBUTING.md)

* [x] I have viewed, signed, and submitted the Contributor License Agreement

* [x] I have made this pull request to the `master` branch

* [x] I have run all the unit tests using `bundle exec rake`

* [x] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng#cf-acceptance-tests-cats)

### CODE REVIEW

**Comment by bingosummer** [comment]
CC: @zrob @dsboulder

**Comment by bingosummer** [comment]
@tcdowney 
Can cloud_controller_ng team please have a review at the PR? You can get the background in the issue fog/fog-azure-rm#367.

**Comment by tcdowney** [comment]
Hi @bingosummer, we'd like to merge this, but unfortunately our team does not currently have an environment using Azure Storage to validate the change. We're going to need to create one first before we can merge this PR. See https://www.pivotaltracker.com/story/show/157889487

Thanks!

Tim && @ewrenn8

**Comment by bingosummer** [comment]
Thanks a lot for reviewing, @tcdowney .
You may need to create two environments. One is CF on Azure which is using Azure Storage, the other is CF on Azure Stack which is using Azure Stack Storage.

**Comment by charleshansen** [comment]
manually merged in cbece86e57de4b565be069b4e6026ca7a32b6b46

**Pull request closed without merging**
