### PR TITLE
Update fog-azure-rm

### PR DESCRIPTION
**Pull request by stephanme**
- improve debug logging
- add missing timeouts to some blobstore operations

Thanks for contributing to cloud_controller_ng. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:

* An explanation of the use cases your change solves

* Links to any other associated PRs

* [x] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/CONTRIBUTING.md)

* [x] I have viewed, signed, and submitted the Contributor License Agreement

* [x] I have made this pull request to the `main` branch

* [ ] I have run all the unit tests using `bundle exec rake`

* [ ] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng#cf-acceptance-tests-cats)

We have this version of fog-azure-rm running on productive CF foundations and already benefit from extended logging to debug blobstore problems on Azure.

### CODE REVIEW

**Comment by stephanme** [comment]
Requires additionally https://github.com/cloudfoundry/capi-release/pull/185 to get fog debug logs on Azure.

**Comment by Gerg** [comment]
Relevant fog-azure-rm commit: https://github.com/fog/fog-azure-rm/commit/d7299cd889fcc26d07fdc3681b5144063693659b

Is there currently anything that uses the `create_block_blob_timeout` configuration?

Side question: Is there any hope for us getting back onto master, or are we going to be stuck on the cf-specific branch?

**Comment by stephanme** [comment]
As I understand it: 
https://github.com/fog/fog-azure-rm/commit/d7299cd889fcc26d07fdc3681b5144063693659b introduces timeouts on certain blob operations. Parameters like `create_block_blob_timeout` could be used to set a timeout different than the default of 10min. 

We have seen upload operations on Azure that hang for unknown reasons until the CC job timeout of 4h kicks in. The blob operation timeouts on Azure storage api level should prevent this.
The improved debug logging should provide information to understand why blob operations hang/timeout.

cc: @MSSedusch and @Peter-Sternberger who worked on this fog-azure-rm improvement.

**Comment by Gerg** [comment]
If I'm a Cloud Foundry operator and the default timeout is too low, can I configure it to be longer? For example, will passing `create_block_blob_timeout` in the [`fog_connection` manifest property](https://docs.cloudfoundry.org/deploying/common/cc-blobstore-config.html#fog-azure) configure the timeout?

**Comment by Peter-Sternberger** [comment]
@Gerg, w.r.t. your side question: there are no news on our side, as of today there is no plan to work on “getting back onto master” in the near future

**Comment by MSSedusch** [comment]
@Gerg not sure how to configure the timeout in CF. The default timeout is quite high. It assumes a transfer rate of 100KiB/s which I think should be reasonable. This can be adapted in the options of a function, e.g. multipart_save_block_blob

**Comment by stephanme** [comment]
`create_block_blob_timeout` can be configured by the mentioned fog_connection manifest property array. The timeout used by fog-azure-rm is taken from the `options` hash.
E.g. compare https://github.com/fog/fog-azure-rm/blob/d7299cd889fcc26d07fdc3681b5144063693659b/lib/fog/azurerm/requests/storage/create_block_blob.rb#L7-L11 with  https://github.com/fog/fog-azure-rm/blob/fog-arm-cf/lib/fog/azurerm/storage.rb#L105-L109.

The default timeouts work well in our productive CF deployments on Azure.

**Pull request merged**
