### PR TITLE
Return 204 on successful delete

### PR DESCRIPTION
**Pull request by fraenkel**
Fixes issue #449

### CODE REVIEW

**Comment by dieucao** [comment]
@fraenkel I'll post a question to cf-dev about how people feel about making this type of change.
Does this PR affect the async services end points that currently return 202 on deletes? Or is that stuff special cased.

**Comment by fraenkel** [comment]
@dieucao The 201 fiasco only affects related routes. A normal delete always returns a 202 or 204 depending on if it queues a job.

**Comment by dieucao** [comment]
@fraenkel Everyone I've talked to so far that has implemented a client thinks this would be okay to change. 
I'll have the team review.
Thanks!

**Comment by jberkhahn** [comment]
@fraenkel There was a change made in spec/support/legacy_api_dsl.rb that should affect the docs. However when we generate the docs it still shows the expected response status as 201. Fix that up and this looks good.

**Comment by fraenkel** [comment]
I don't know what you are referring to. I rebased the commit and re-pushed. Everything is showing a 204 without any code change.
Please identify the exact command that still shows a 201.

**Comment by rmasand** [comment]
Not seeing the docs issue anywhere, maybe they needed to be regenerated? Also the travis failure from before looked to be a flake. Going to go ahead and merge. Thanks @fraenkel !

**Comment by dieucao** [comment]
This will be available in the next cf-release.

**Pull request merged**
